### ISSUE TITLE
[Carousel] SlingException on saving edit dialog

### ISSUE THREAD

**Issue by richardhand** [adobe/aem-core-wcm-components#549] opened 2019-04-17 11:44 UTC
### Bug Report

moved here from #533.

Issue encountered when carousel core component is proxied /apps/abc/components/content/corecarousel/v1/carousel
sling:resourceSupertype = /apps/core/wcm/components/carousel/v1/carousel

**Current Behavior** 
On saving the dialog properties, an exception appears on the page - "org.apache.sling.api.SlingException: Exception during response processing"
On trying multiple times, this exception does not appear and dialog closes. Check the snapshot.

**Expected Behavior**
The dialog should close at one attempt without any exceptions.

**Environment**
- AEM 6.3.3
- Core Components version 2.2.2
- Java(TM) SE Runtime Environment (build 1.8.0_201-b09)

**Additional context / Screenshots**
![55637500-d5a38680-57e2-11e9-8ad8-d9ad59fcab46](https://user-images.githubusercontent.com/25616660/56285280-1ff80200-6117-11e9-962c-8d69ac547d51.png)

**Comment by richardhand** [comment] 2019-04-17 12:03
Hi @kanika1901kapoor, I separated your original bug report into two separate issue so we can focus on each and track them separately (and updated the original title and description in #533). Hope you don't mind.

For both, I have also been unable to replicate them and would therefore like to try and find out a little more:

* Are you able to reproduce the issue consistently? e.g: every time you open and save the dialog, or just sometimes? Is it always the first save attempt in a dialog session that fails - and thereafter the error isn't shown? Do you see the error even if no updates have been made to the input fields?
* If it can be reproduced consistently, could you provide the exact steps taken to do so.
* Which browser(s) are you seeing the problem on?

**Comment by kanika1901kapoor** [comment] 2019-04-23 11:32
@richardhand Are you not able to reproduce with 6.3.3 and core components 2.2.2?

Answers to your questions:
1. Are you able to reproduce the issue consistently? Answer: just sometimes on saving the dialog

2. Is it always the first save attempt in a dialog session that fails - and thereafter the error isn't shown?  There is no first save attempt pattern. It just occurs sometimes on saving the dialog.

3. Do you see the error even if no updates have been made to the input fields? Yes.

4. Which browser(s) are you seeing the problem on? Chrome and firefox both.

**Comment by gabrielwalt** [comment] 2020-08-31 17:16
Closing this for now as there hasn't been activity for over a year.
Please create a support issue if your project needs immediate action on this.

**Closed by gabrielwalt** 2020-08-31 17:16 UTC
Labels: to clarify
