### ISSUE TITLE
[Accessibility] Search trap using TAB key

### ISSUE THREAD

**Issue by dingrassia** [adobe/aem-core-wcm-components#1559] opened 2021-05-11 14:30 UTC
I'm reopening the issue after checks suggested on https://github.com/adobe/aem-core-wcm-components/issues/1553.

**Current Behavior**
When you land on a page with the Quick Search component and try to use the TAB key to navigate through the site it will get stuck on the Search input field. This wrong behavior disappears when you click outside the Quick Search input: trying again to navigate the site using the TAB key, it will focus on the input field only once and then it proceeds to the next element as normally expected.

**Expected behavior/code**
Using the TAB key the user should be able to navigate the website and when he/she lands on the Quick Search should proceed to the next element clicking the TAB key another time.

**Environment**

- AEM as a Cloud Service SDK v2021.2.4944.20210221T230729Z-210128
- Core Components version 2.16.0 (manually updated and verified)
- Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)

The error can be noticed on https://wknd.site too.

**Comment by msagolj** [comment] 2021-05-12 15:07
Still not reproducible for me on 2.16 (see attached video). Updating core components can be a bit tricky with a SDK instance as its already part of the SDK. Did you follow the instructions mentioned here:
https://github.com/adobe/aem-core-wcm-components/blob/master/BUILDING.md#aem-as-a-cloud-service-sdk
especially :
- make sure you delete or disable the aem-precompiled-scripts in /system/console
- the only one version of the core component bundles is running (/system/console, search for 'core wcm')
- that its installed under /libs/core/wcm and not /apps/core/wcm (should only contain config files)

[tab_search.zip](https://github.com/adobe/aem-core-wcm-components/files/6467091/tab_search.zip)

**Comment by dingrassia** [comment] 2021-05-20 15:29
Hi,

tried again but nothing:
- I checked the bundle, the only one active was 2.16.0;
- disabled aem-precompiled-scripts;
- checked to have only the core components below /libs

Still not working, tried to keep the /apps one instead (since the core components packages write below /apps) but nothing changed

**Comment by msagolj** [comment] 2021-05-25 13:38
> Still not working, tried to keep the /apps one instead (since the core components packages write below /apps) but nothing changed

As mentioned in https://github.com/adobe/aem-core-wcm-components/blob/master/BUILDING.md#aem-as-a-cloud-service-sdk, you have to use the `-Pcloud` profile to build the components, this way they get build so they installed under /libs.

Other then that i tested again with latest release 2.6.4 with FF, IE and Chrome using a project created with archetype. So im not sure where the issue is right now. what are you testing with ? do you have a video or so ?

**Comment by gabrielwalt** [comment] 2022-01-05 09:20
Waiting for instructions to reproduce since May 2021, closing this for now as we cannot reproduce it.

**Closed by gabrielwalt** 2022-01-05 09:20 UTC
Labels: needs-clarification
