### ISSUE TITLE
Maven config and subpackage directive doesn't install core components

### ISSUE THREAD

**Issue by josephh** [adobe/aem-core-wcm-components#213] opened 2018-06-15 11:34 UTC
## Bug Report

**Current Behavior**
Using Maven to build custom code, incorporating core wcm components all, doesn't result in core components auto-installation.  
Following this project's readme instructions: including core components as a Maven dependency and a subPackage entry for use by com.day.jcr.vault:content-package-maven-plugin results in a zip file that includes the core.wcm.components.all-1.1.0.zip (under jcr_root/etc/packages/adobe/cq60) but this is not shown in package manager or added to the content tree.
**Expected behavior/code**
Expect this package to show in package manager and content tree - similar to a manual upload and install of the zip.  Am i missing something (similar acs commons auto installs OK for me with (though my build also separately embeds acs bundle jar)) 

**Environment**
AEM 6.3 SP1
- Core Components version 1.1.0
- Java(TM) SE Runtime Environment (build 1.8.0_152-b16)

**Comment by bpauli** [comment] 2018-06-15 12:37
@josephh Can you please share your pom.xml, so we can try to reproduce the issue? Thanks!

**Comment by josephh** [comment] 2018-06-15 14:06
@bpauli sure i'll get the pom together and add it here

**Comment by josephh** [comment] 2018-06-16 11:38
Here you go @bpauli.  Fairly standard I imagine (think this project probably originated via an archetype).
(parent pom declares the core-components-all dependency in the dependencyManagement section... 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>foo-aem</artifactId>
        <groupId>com.bar.foo</groupId>
        <version>1.2.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>content-package</packaging>

    <artifactId>foo-components</artifactId>
    <name>Simply Health - AEM Templates and Components</name>

    <dependencies>
        <dependency>
            <groupId>com.bar.foo</groupId>
            <artifactId>foo-services</artifactId>
            <version>1.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.connectors</groupId>
            <artifactId>jersey-apache-connector</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient-osgi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.commons-beanutils</artifactId>
        </dependency>
        <dependency>
            <groupId>com.adobe.acs</groupId>
            <artifactId>acs-aem-commons-bundle</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eclipsesource.jaxrs</groupId>
            <artifactId>jersey-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.adobe.acs</groupId>
            <artifactId>acs-aem-commons-content</artifactId>
            <version>3.9.0</version>
            <type>content-package</type>
            <classifier>min</classifier>
        </dependency>
        <dependency>
            <groupId>com.adobe.cq</groupId>
            <artifactId>core.wcm.components.all</artifactId>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.jsoup</artifactId>
        </dependency>
    </dependencies>

    <!-- ====================================================================== -->
    <!-- B U I L D   D E F I N I T I O N                                        -->
    <!-- ====================================================================== -->
    <build>
        <resources>
            <!-- define the resources that will go into the package -->
            <resource>
                <directory>${basedir}/src/main/content/META-INF</directory>
                <targetPath>../vault-work/META-INF</targetPath>
            </resource>
            <resource>
                <directory>${component.lib.dist.dir}</directory>
                <targetPath>${project.build.directory}/classes/etc/designs/foo/assets</targetPath>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>${basedir}/src/main/content/jcr_root</directory>
                <excludes>
                    <!-- exclude .vlt control files in the package -->
                    <exclude>**/.vlt</exclude>
                    <exclude>**/.vltignore</exclude>
                    <exclude>**/.gitignore</exclude>
                    <exclude>**/*.iml</exclude>
                    <exclude>**/.classpath</exclude>
                    <exclude>**/.project</exclude>
                    <exclude>**/.settings</exclude>
                    <exclude>**/.DS_Store</exclude>
                    <exclude>**/target/**</exclude>
                    <exclude>**/pom.xml</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <!-- ensure that the empty directories are copied -->
                <configuration>
                    <includeEmptyDirs>true</includeEmptyDirs>
                </configuration>

                <executions>
                    <execution>
                        <id>copy-metainf-vault-resources</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/vault-work/META-INF</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${basedir}/META-INF</directory>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-runmode-configs</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/classes/apps/foo</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${basedir}/src/main/conf</directory>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- ====================================================================== -->
            <!-- FRONT END TOOLS                                                        -->
            <!-- ====================================================================== -->
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>

                <!-- optional -->
                <configuration>
                    <workingDirectory>${component.lib.working.dir}</workingDirectory>
                </configuration>

                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>

                        <!-- optional: default phase is "generate-resources" -->
                        <phase>generate-resources</phase>

                        <configuration>
                            <!-- i.e. node LTS v8.9.4 (npm v5.6.0) -->
                            <nodeVersion>v8.9.4</nodeVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install cli login</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>

                        <!-- optional: default phase is "generate-resources" -->
                        <phase>generate-resources</phase>

                        <configuration>
                            <arguments>install npm-cli-login --no-save</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm login</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>

                        <!-- optional: default phase is "generate-resources" -->
                        <phase>generate-resources</phase>

                        <configuration>
                            <arguments>run-script login --
                                -u ${npm.username}
                                -p ${npm.password}
                                -e ${npm.email}
                                --config-path ${component.lib.working.dir}/.npmrc
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>

                        <!-- optional: default phase is "generate-resources" -->
                        <phase>generate-resources</phase>

                        <configuration>
                            <!-- optional: The default argument is actually
                            "install", so unless you need to run some other npm command,
                            you can remove this whole <configuration> section.
                            -->
                            <arguments>install @foo/component-library@${component.lib.version} --no-save --production</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            
            <!-- ====================================================================== -->
            <!-- V A U L T   P A C K A G E   P L U G I N                                -->
            <!-- ====================================================================== -->

            <plugin>
                <groupId>com.day.jcr.vault</groupId>
                <artifactId>content-package-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <filterSource>${basedir}/META-INF/vault/filter.xml</filterSource>
                    <verbose>true</verbose>
                    <failOnError>true</failOnError>
                    <group>foo</group>
                    <properties>
                        <acHandling>Merge</acHandling>
                    </properties>
                    <embeddeds>
                        <embedded>
                            <groupId>com.bar.foo</groupId>
                            <artifactId>foo-services</artifactId>
                            <target>/apps/foo/install</target>
                        </embedded>
                        <embedded>
                            <groupId>com.eclipsesource.jaxrs</groupId>
                            <artifactId>jersey-all</artifactId>
                            <target>/apps/foo/install</target>
                        </embedded>
                        <embedded>
                            <groupId>org.glassfish.jersey.connectors</groupId>
                            <artifactId>jersey-apache-connector</artifactId>
                            <target>/apps/foo/install</target>
                        </embedded>
                        <embedded>
                            <groupId>org.apache.httpcomponents</groupId>
                            <artifactId>httpclient-osgi</artifactId>
                            <target>/apps/foo/install</target>
                        </embedded>
                        <embedded>
                            <groupId>org.glassfish.jersey.bundles.repackaged</groupId>
                            <artifactId>jersey-guava</artifactId>
                            <target>/apps/foo/install</target>
                        </embedded>
                        <embedded>
                            <groupId>org.apache.servicemix.bundles</groupId>
                            <artifactId>org.apache.servicemix.bundles.commons-beanutils</artifactId>
                            <target>/apps/foo/install</target>
                        </embedded>
                        <embedded>
                            <groupId>com.adobe.acs</groupId>
                            <artifactId>acs-aem-commons-bundle</artifactId>
                            <target>/apps/foo/install</target>
                        </embedded>
                        <embedded>
                             <groupId>org.apache.servicemix.bundles</groupId>
                                <artifactId>org.apache.servicemix.bundles.jsoup</artifactId>
                            <target>/apps/foo/install</target>
                        </embedded>
                    </embeddeds>
                    <subPackages>
                        <subPackage>
                            <groupId>com.adobe.acs</groupId>
                            <artifactId>acs-aem-commons-content</artifactId>
                            <filter>true</filter>
                        </subPackage>
                        <subPackage>
                            <groupId>com.adobe.cq</groupId>
                            <artifactId>core.wcm.components.all</artifactId>
                            <filter>true</filter>
                        </subPackage>
                    </subPackages>
                    <version>${package.version}</version>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>autoInstallPackage</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.day.jcr.vault</groupId>
                            <artifactId>content-package-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>install-package</id>
                                    <goals>
                                        <goal>install</goal>
                                    </goals>
                                    <configuration>
                                        <targetURL>http://${aem.host}:${aem.port}/crx/packmgr/service.jsp</targetURL>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>autoInstallPackagePublish</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.day.jcr.vault</groupId>
                        <artifactId>content-package-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>install-package</id>
                                <goals>
                                    <goal>install</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <targetURL>http://${aem.publish.host}:${aem.publish.port}/crx/packmgr/service.jsp</targetURL>
                            <userId>${aem.publish.user}</userId>
                            <password>${aem.publish.password}</password>
                            <failOnError>true</failOnError>
                            <failOnMissingEmbed>true</failOnMissingEmbed>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
```

**Comment by gabrielwalt** [comment] 2018-06-22 11:48
(CQ-4247324)

**Comment by vladbailescu** [comment] 2018-11-07 12:03
@josephh, did you manage to get past this issue? I just tested with a simplified config based on your pom.xml and both ACS and Core Components packages install normally:

![image](https://user-images.githubusercontent.com/3670963/48130447-5fcbdb00-e295-11e8-8dee-97ba8d63a8d4.png)

Here's the `pom.xml` I used:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <groupId>com.bar.foo</groupId>
    <artifactId>foo-components</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <modelVersion>4.0.0</modelVersion>
    <packaging>content-package</packaging>

    <dependencies>
        <dependency>
            <groupId>com.adobe.acs</groupId>
            <artifactId>acs-aem-commons-bundle</artifactId>
            <version>3.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.adobe.acs</groupId>
            <artifactId>acs-aem-commons-content</artifactId>
            <version>3.9.0</version>
            <type>content-package</type>
            <classifier>min</classifier>
        </dependency>
        <dependency>
            <groupId>com.adobe.cq</groupId>
            <artifactId>core.wcm.components.all</artifactId>
            <version>2.2.0</version>
            <type>zip</type>
        </dependency>
    </dependencies>

    <!-- ====================================================================== -->
    <!-- B U I L D   D E F I N I T I O N                                        -->
    <!-- ====================================================================== -->
    <build>
        <resources>
            <!-- define the resources that will go into the package -->
            <resource>
                <directory>${basedir}/src/main/content/META-INF</directory>
                <targetPath>../vault-work/META-INF</targetPath>
            </resource>
            <resource>
                <directory>${component.lib.dist.dir}</directory>
                <targetPath>${project.build.directory}/classes/etc/designs/foo/assets</targetPath>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>${basedir}/src/main/content/jcr_root</directory>
                <excludes>
                    <!-- exclude .vlt control files in the package -->
                    <exclude>**/.vlt</exclude>
                    <exclude>**/.vltignore</exclude>
                    <exclude>**/.gitignore</exclude>
                    <exclude>**/*.iml</exclude>
                    <exclude>**/.classpath</exclude>
                    <exclude>**/.project</exclude>
                    <exclude>**/.settings</exclude>
                    <exclude>**/.DS_Store</exclude>
                    <exclude>**/target/**</exclude>
                    <exclude>**/pom.xml</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
             <!-- ====================================================================== -->
            <!-- V A U L T   P A C K A G E   P L U G I N                                -->
            <!-- ====================================================================== -->
            <plugin>
                <groupId>com.day.jcr.vault</groupId>
                <artifactId>content-package-maven-plugin</artifactId>
                <version>0.0.24</version>
                <extensions>true</extensions>
                <configuration>
                    <filterSource>${basedir}/META-INF/vault/filter.xml</filterSource>
                    <verbose>true</verbose>
                    <failOnError>true</failOnError>
                    <group>foo</group>
                    <properties>
                        <acHandling>Merge</acHandling>
                    </properties>
                    <embeddeds>
                         <embedded>
                            <groupId>com.adobe.acs</groupId>
                            <artifactId>acs-aem-commons-bundle</artifactId>
                            <target>/apps/foo/install</target>
                        </embedded>
                    </embeddeds>
                    <subPackages>
                        <subPackage>
                            <groupId>com.adobe.acs</groupId>
                            <artifactId>acs-aem-commons-content</artifactId>
                            <filter>true</filter>
                        </subPackage>
                        <subPackage>
                            <groupId>com.adobe.cq</groupId>
                            <artifactId>core.wcm.components.all</artifactId>
                            <filter>true</filter>
                        </subPackage>
                    </subPackages>
                    <version>${package.version}</version>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>autoInstallPackage</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.day.jcr.vault</groupId>
                            <artifactId>content-package-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>install-package</id>
                                    <goals>
                                        <goal>install</goal>
                                    </goals>
                                    <configuration>
                                        <targetURL>http://localhost:4502/crx/packmgr/service.jsp</targetURL>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>
</project>
```

I'm closing this as *cannot reproduce*, please reopen with extra information in case you're still having problems with this.

**Closed by vladbailescu** 2018-11-07 12:03 UTC
Labels: to clarify
