### ISSUE TITLE
[Carousel] Console error on child reorder

### ISSUE THREAD

**Issue by kanika1901kapoor** [adobe/aem-core-wcm-components#533] opened 2019-04-05 15:17 UTC
## Bug Report 

Issue encountered when carousel core component is proxied /apps/abc/components/content/corecarousel/v1/carousel
sling:resourceSupertype = /apps/core/wcm/components/carousel/v1/carousel
![image](https://user-images.githubusercontent.com/1798869/55638072-ff10e200-57e3-11e9-8105-74cd100479dd.png)

**Environment**
- AEM 6.3.3
- Core Components version 2.2.2 
- Java(TM) SE Runtime Environment (build 1.8.0_201-b09)

**Current Behavior**
The reordering does not work through "Select Panel" (option 2 ) or through "Configure"(option 1) in dialog toolbar.

**Expected Behavior**
Reordering of components inside carousel should work through dialog and panel.

![image](https://user-images.githubusercontent.com/1798869/55637861-9d507800-57e3-11e9-895d-61dca49cc734.png)

![image](https://user-images.githubusercontent.com/1798869/55637962-c6710880-57e3-11e9-83a5-b8cd78e514e4.png)

![image](https://user-images.githubusercontent.com/1798869/55637984-d38df780-57e3-11e9-81a4-755cf85f41b3.png)

**Comment by msagolj** [comment] 2019-04-08 14:59
I tested quickly and it works for me. When the sorting is not working its usually a sign that you forgot to add carousel editing listeners as described in [Enabling Carousel editing functionality](https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel#enabling-carousel-editing-functionality) 

Simply copy the cq:EditConfig node from the Carousel core component to your proxy component, see We.Retail for example:

![image](https://user-images.githubusercontent.com/37147400/55734216-754d5880-5a1f-11e9-8db6-d55b77a664a3.png)

Closing issue. If issue is still occurring please reopen and list any js errors shown in browser console.

**Comment by kanika1901kapoor** [comment] 2019-04-11 07:25
@msagolj I tried again with edit listeners, but both the issues mentioned above still persist.
This is AEM version 6.3.3

Please see the console error below:
_**Request URL** http://localhost:4502/content/abc/accordion-sample/_jcr_content/root/responsivegrid/carousel
**Request Method** POST
**Status Code** 500
**Error Message** org.apache.sling.api.SlingException: Exception during response processing._

**Comment by richardhand** [comment] 2019-04-17 12:15
@kanika1901kapoor - I moved "issue 2" to #549.

For this issue, I'm again unable to replicate the behaviour, so would like to find out a little more about the behaviour:

* Are you able to reproduce the issue consistently? e.g: every time you reorder the items in the panel select or dialog you see the console error?
* If it can be reproduced consistently, could you provide the exact steps taken to do so?
* Which browser(s) are you seeing the problem on?

**Comment by gabrielwalt** [comment] 2019-07-02 16:50
Closing this issue for now. Please reopen if you have more details about how to reproduce it.

**Closed by gabrielwalt** 2019-07-02 16:50 UTC
Labels: to clarify
