### ISSUE TITLE
[Teaser] Enable Call To Action does not enables multifield with links on dialog load

### ISSUE THREAD

**Issue by marekczajkowski** [adobe/aem-core-wcm-components#1457] opened 2021-03-23 11:14 UTC
### Expected Behaviour
When opening teaser dialog multifield with links is enabled if checkbox Call To Action is checked

### Actual Behaviour
When opening teaser dialog multifield with links is disabled if checkbox Call To Action is checked

#### Steps to Reproduce
1. Create teaser component.
2. Check Call To Action Checkbox and configure some links below.
3. Save the changes.
4. Reload the page
5. Open dialog of configured teaser
6. Verify that links can not be edited until user check/uncheck Call To Action

#### Platform and Version
AEM 6.5
Core Component 2.13.2
#### Code responsible for the problem
/apps/core/wcm/components/teaser/v1/teaser/clientlibs/editor/js/teaser.js

#### Possible solution
call toggleInputs function after actionsEnabled is determined

**Comment by gabrielwalt** [comment] 2021-08-03 09:59
Cannot reproduce anymore, closing this as it seems to have been fixed meanwhile.

**Closed by gabrielwalt** 2021-08-03 09:59 UTC
Labels: bug
