### ISSUE TITLE
[Text] Linking to content in inline mode does not work after SP2

### ISSUE THREAD

**Issue by jakublamprecht** [adobe/aem-core-wcm-components#801] opened 2019-10-15 11:36 UTC
## Bug Report

**Current Behavior**
Currently the path picker for links in Text component editor does not work. It stopped working after installing SP2 for AEM 6.5. When the button that should open the picker is clicked, an error with status 404 and message "Resource at '/mnt/overlay/cq/gui/content/linkpathfield/picker.html' not found: No resource found" is thrown. I checked it on 6.5 with SP1 version and it works there.

**Expected behavior/code**
When clicking path picker, the picker should open.

**Environment**
- AEM 6.5 SP2
- Core Components version 2.6.0 and 2.7.0

**Comment by richardhand** [comment] 2019-10-15 21:03
@jakublamprecht - I've been unable to replicate this on 6.5.2 with Core Components 2.7.0. If the problem persists for you, as it appears to be an issue in the rich text editor in the product rather than the Core Text component, it would be best reported via [Adobe Enterprise Support](https://helpx.adobe.com/contact/enterprise-support.ec.html).

**Comment by jakublamprecht** [comment] 2019-10-16 09:02
I just double checked that and I'm pretty sure that it stops working after updating to 6.5.2 (checked that with both Core Components 2.6.0 and 2.7.0). We reported a daycare issue aswell (Ticket Id: 195235). Here's a GIF of that issue:
![LinkTextISsue](https://user-images.githubusercontent.com/18114264/66904377-41717200-f004-11e9-8bf8-defab2ae3291.gif)

**Comment by msagolj** [comment] 2019-10-17 08:16
As @richardhand mentioned its an issue with the rich text editor and @jakublamprecht already opened a daycare issue where the issue is currently being looked at i will close this one.

**Closed by msagolj** 2019-10-17 08:16 UTC
Labels: to clarify

**Comment by MalteHer** [comment] 2019-12-06 08:50
Any updates here? We have the same problem, I just installed a fresh instance of 6.5 and then installed first SP1 and then SP2, it definitely stopped working after SP2.

**Comment by steveychan** [comment] 2019-12-07 00:11
I ran into the same issue and I found that the "cq-ui-wcm-editor-content-1.1.294.zip" package (SP2) was indicated as installed, but the content "/libs/cq/gui/content/linkpathfield" was missing.  I was able to fix the issue by reinstalling the package.  Hope this helps.
