### ISSUE TITLE
[Image] Does not call resourceResolver.map() - /content/<project>/<language> paths used on publish

### ISSUE THREAD

**Issue by henrykuijpers** [adobe/aem-core-wcm-components#60] opened 2017-09-07 14:07 UTC
When the image component is used on a page, resourceResolver.map() is not being called when determining the smart images. 

Result:
`<noscript data-cmp-image="{&#34;smartImages&#34;:[&#34;/content/project/nl/jcr%3acontent/banner.img.320.jpg&#34;,&#34;/content/project/nl/jcr%3acontent/banner.img.480.jpg&#34;,&#34;/content/project/nl/jcr%3acontent/banner.img.640.jpg&#34;,&#34;/content/project/nl/jcr%3acontent/banner.img.768.jpg&#34;,&#34;/content/project/nl/jcr%3acontent/banner.img.1024.jpg&#34;,&#34;/content/project/nl/jcr%3acontent/banner.img.1152.jpg&#34;,&#34;/content/project/nl/jcr%3acontent/banner.img.1440.jpg&#34;,&#34;/content/project/nl/jcr%3acontent/banner.img.1600.jpg&#34;],&#34;smartSizes&#34;:[320,480,640,768,1024,1152,1440,1600],&#34;lazyEnabled&#34;:true}">
   <img src="/content/project/nl/_jcr_content/banner.img.jpg" alt/>
   </noscript>`

It seems to me that the resource resolved map'd URLs should be used, i.e. in this case:
/nl/_jcr_content/banner.img.320.jpg

**Comment by richardhand** [comment] 2017-09-28 13:32
Thanks @henrykuijpers, we agree and have added this improvement to our roadmap.

**Comment by henrykuijpers** [comment] 2018-03-13 13:47
I'm not sure I agree anymore. :)

I just ran into an issue where someone had configured a sling:alias with spaces inside. The path that had this sling:alias configured was used in an href-attribute on an a-tag..

Now the issue was that we were calling resourceResolver.map() on it twice: Once via the ootb LinkChecker, and the second time via the ResourceResolverMapTransformerFactory from ACS AEM Commons. 

This caused the URL to get rewritten from '/content/my/page.html' to '/content/my/aliassed%20page.html', which is fine. But then when the second map() call was done, it was rewritten to '/content/my/aliassed%2520page.html'.

So the question that we should raise here is: Who is responsible for calling resourceResolver.map()? 
* The developer's own code, if it's not about a:href?
* A generic service that can be configured to call resourceResolver.map() on any element and any attribute (that would be my preference)?

What is the recommendation from Adobe?

And how do you handle the case with spaces I explained above here? Apparently calling resourceResolver.map() multiple times can have side-effects that are not wanted.

**Comment by henrykuijpers** [comment] 2018-03-13 13:51
Also, it could be that this issue becomes irrelevant, since the data-cmp-image-attribute is now rewritten to a more clean format, as explained in https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/issues/72

**Comment by raducotescu** [comment] 2018-03-29 08:56
@henrykuijpers, I think the issue is still valid, but not with this limited scope. All URLs should be handled uniformly and allow the use of vanity paths. I guess the right solution is #63, where vanity paths should also be handled correctly.

**Comment by henrykuijpers** [comment] 2018-03-29 09:11
I believe issue #63 is about links that need to be externalized. I.e. the link that you would provide to a social share component, or the link that you would put in an og:image metadata attribute.

This issue is about the default linkchecker (and its rewriter) not mapping the paths that exist in the json-data on the image component tag. 

The markup has now changed, but still, the issue remains: 
Who is responsible for applying the sling mappings for anything other than a:href? 
1. A component itself? 
2. Something like the ResourceResolverMapTransformerFactory?

Calling resourceResolver.map() twice can result in double encoded characters (i.e. the % sign).

**Comment by gabrielwalt** [comment] 2018-06-21 10:32
(CQ-4221415)

**Comment by kwin** [comment] 2018-11-08 13:29
Just for the record: The default link checker in AEM will only map links containing the extension ".html" so I don't think we have an issue here with duplicate mapping  because all image URL will never have the extension ".html". Also the default link checker will be default only rewrite the following elements/attributes: `a:href, area:href, form:action`.

**Comment by richardhand** [comment] 2018-11-08 13:38
@kwin looks like there's also been an effort in `ResourceResolverMapTransformerFactory` to prevent double encoding with https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1464

I would say we should map the URLs within Core Components for patterns not supported in the default link checker. We can't expect a user to depend on ACS commons.

At the project level whether to map would be a decision based on whether or not such a service is in use. Given the above change in the `ResourceResolverMapTransformerFactory` seems like we would be safe anyway if this is already in use.

Although I haven't tested it.

**Comment by kwin** [comment] 2018-11-08 13:49
Calling ResourceResolver.map() twice might in the worst case still lead to 404s. This is rather because the URI encoding will then happen twice. The ResourceResolver.map will internally call https://github.com/apache/sling-org-apache-sling-resourceresolver/blob/e017ace802aa55805727bd6f5637939599d19ac4/src/main/java/org/apache/sling/resourceresolver/impl/mapping/ResourceMapperImpl.java#L362 which does URI encoding.

**Comment by richardhand** [comment] 2018-11-08 13:56
If we add mapping in the image component (`ResourceResolver.map()`) on our `data-cmp-src` attribute value, where do you see the double mapping occurring?

**Comment by kwin** [comment] 2018-11-08 14:00
If someone adds a custom second rewriter which does additional mapping and doesn't explicitly call URL decoding on that (as the ACS rewriter does in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/d8201d0a76dfb0a8c5a83bd4e05e8a701bc3333c/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/ResourceResolverMapTransformerFactory.java#L105) you might still end up with 404s. But this is not very likely.

**Comment by richardhand** [comment] 2018-11-08 14:04
Given the could-be-slings-fault issue with double encoding when calling `ResourceResolver.map()` I  would say it's the responsibility of such a rewriter to handle decoding as ACS commons do. If it's known that the image component rewrites its attribute, there would be no need to register our attribute with a rewriter in any case.

So I would recommend we go ahead and do the mapping here.

**Comment by richardhand** [comment] 2018-11-08 15:54
We already map the `baseResourcePath` at https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/ImageImpl.java#L204

Do you see anything missing @kwin, if not, I will close this.

**Comment by henrykuijpers** [comment] 2018-11-08 16:03
Looks like this was added in 
9cb5ffb1335777c482ca0b66db762f6fe41f734d

Which is way after this ticket was created, for a different issue. So this can be closed now.

**Closed** 2018-11-08 16:06 UTC
Labels: bug

**Comment by kwin** [comment] 2018-11-08 16:08
@richardhand Can you adjust the fix version then? Seems this was fixed with 2.0.4.

**Comment by henrykuijpers** [comment] 2018-11-08 16:22
It is also rather strange that this was fixed in the v1 component with the 2.0.4 version, or not? 

I thought the intention was to keep the versioned components isolated, so code changes would not affect the old components, but instead introduce a new version explicitly, or am I wrong here?

**Comment by richardhand** [comment] 2018-11-08 16:31
The V2 image component implementation extends the V1 equivalent so as not to repeat much of the handling. Therefore, the fix is available in both versions. Changes we make in the V2 implementation won't affect the V1 component as its bound to the V2 resource type.

**Comment by henrykuijpers** [comment] 2018-11-08 16:33
But, this change actually introduces a regression in the v1 component (even though this regression isn't so bad). I'm just curious on your opinion on that.

**Comment by vladbailescu** [comment] 2018-11-08 16:35
I think at that point we viewed it as fixing a bug and not adding a change/improvement.
