### ISSUE TITLE
[ContentFragment] rawcontent selector outputs HTML

### ISSUE THREAD

**Issue by aguacatedan** [adobe/aem-core-wcm-components#504] opened 2019-03-12 20:28 UTC
## Bug Report

**Current Behavior**
When using the rawcontent selector to render the content fragment, it outputs the text contents inside of `p` tags.
The Multiline Content Fragment Model element allows the use of richtext or plaintext. In our case, we're looking to use Plaintext to avoid the wrapping HTML tags the Richtext editor adds, but the rawcontent script transforms it into HTML, resulting in text wrapped in a `p` tag.

**Expected behavior/code**
The rawcontent selector should display the text exactly as it's stored in the JCR without enforcing the conversion of text to HTML

**Environment**
- AEM 6.4 SP3
- Core Components version 2.3.0
- JRE version 1.8

**Possible Solution**
Use `getValue()` instead of `getHtml()` in the rawcontent script.
When using the Multiline element, it defaults to richtext so any content is saved to the JCR wrapped in `p` tags. No need to enforce the transformation.

**Comment by vladbailescu** [comment] 2019-03-20 14:51
@stefangrimm , you probably know more about how this was designed and where it might be already used. Could you look into this request? Thanks!

**Comment by stefangrimm** [comment] 2019-03-20 16:05
The `rawcontent` selector is designed for a very narrow use-case: To create a HTML representation of the actual component output for _internal use only_. It has to be done in a such complicated way as only the component "knows" how the rendering will occur and what the corresponding output eventually is. The result has to be returned in a specific way (HTML, &lt;p&gt; tags etc.) to make these internals work correctly.

The `rawcontent` selector is not supposed to be used directly (not sure if we can document this somewhere or annotate the code accordingly), so I'm wondering what the actual use-case is and if the usage of `.model.json` would be a better fit - if the use-case is about requesting something with the `rawcontent` selector directly.

If it is about getting the plain text into a regular HTML page (rendered by AEM), you could try the following (but you will lose any additional functionality that depends on the `rawcontent` rendering):

- In the "Properties" dialog, change the display mode to "Multiple Elements"
- Add the element that you want to output to the list of elements
- Save the properties (a manual reload of the page may be required)

The output should now circumvent the `rawcontent` stuff and provide you with the desired raw output, be it HTML, plain text or Markdown. But note that still some markup (`dl`, `dt`, `dd` IIUC)  is created "around" the raw text (by design). IIRC you are supposed to use CSS to style the content, e.g. to hide the element name in the output.

If you need more customization, maybe using the Core Component is the wrong way to go. You may want to extend it. Or - if it's just about dumping raw content into a page - a simple custom component leveraging the Content Fragments Java API should be easy to implement and could be an alternative as well.

**Comment by vladbailescu** [comment] 2019-03-21 12:11
@aguacatedan , closing this, please use one of the solutions proposed by @stefangrimm!

**Closed by vladbailescu** 2019-03-21 12:11 UTC
Labels: to clarify
