### ISSUE TITLE
[Accessibility] [Advisory][Carousel] Linked images in carousel have name announced twice by screen reader.

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1786] opened 2021-08-27 00:21 UTC
**Steps to Reproduce**
1. Enable NVDA screen reader.
2. Open page in Google Chrome.
3. Use TAB or SHIFT + TAB to navigate to the linked images in the "Teaser Slides" carousel.

**Current Behavior**
Due to a redundant `title` attribute in the `img` element, the image link is read twice. For example: "Lava flowing into the ocean graphic Lava flowing into the ocean link".

**Expected behavior/code**
Ensure that textual alternatives are concise and descriptive. Avoid duplicating the alt text in the title attribute.

**Environment**
Chrome 92, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Without Vision; Limited Vision; Limited Manipulation

**WCAG SC**
2.4.4 Link Purpose (In Context)(Advisory Only)

**Code snippet**
```
<img src="/content/core-components-examples/library/container/carousel/_jcr_content/root/responsivegrid/demo/component/carousel_8337507762/teaser_720124833.coreimg.jpeg" class="cmp-image__image" itemprop="contentUrl" data-cmp-hook-image="image" alt="Lava flowing into the ocean" title="Lava flowing into the ocean">
```
**Possible Solution**
Remove the `title` attribute from the image.

**Comment by richardhand** [comment] 2021-09-01 15:11
@adobe export issue to Jira project SITES

**Comment by gabrielwalt** [comment] 2022-01-07 09:26
This is because the carousel items are constructed with teasers, so this bug is a duplicate of #1712.

**Closed by gabrielwalt** 2022-01-07 09:26 UTC
Labels: enhancement
