### ISSUE TITLE
Image Component: Set option to choose Target attribute to _blank and _self

### ISSUE THREAD

**Issue by vineetkaushikmca** [adobe/aem-core-wcm-components#909] opened 2020-02-11 09:51 UTC
1.  There should be option to choose to open in same/new tab after clicking on image

**Comment by bartoszglow** [comment] 2020-02-11 11:19
Thanks for your feedback. We are currently working on standardization of link handling (#713). That will be implemented in v3 of image component. As part of link standardization we plan to have additional option to set target property for an anchor so that will address your issue.

**Comment by gabrielwalt** [comment] 2020-03-11 11:14
Closing this issue as a duplicate of #713.

**Closed by gabrielwalt** 2020-03-11 11:14 UTC
Labels: enhancement
