### ISSUE TITLE
[Teaser] Policy 'Don't link image' doesn't work when link is added (without CTA option)

### ISSUE THREAD

**Issue by patrycjakurkowiak** [adobe/aem-core-wcm-components#695] opened 2019-08-14 12:01 UTC
## Bug Report

**Current Behavior - steps to reproduce:**
1. Teaser component is configure with link (CTA is not defined)
2. Policy related to Teaser component contains checked property 'Don't link image'

**Actual results:**
Teaser component contains link on Image and on Title in this case. It causes issue 'Redundant link'.

**Expected behavior/code**
I expect that Image is not a link on Teaser component. Please explain whether there is any reason that it works in this way.

**Environment**
AEM version 6.5.0
Core Components 2.5.0

**Comment by msagolj** [comment] 2019-08-15 13:25
@patrycjakurkowiak I can't reproduce the issue you described, see attached video.

Closing issue for now. If you still have the issue please reopen and explain any differences to the steps taken in the video.

[dontlinkimage.zip](https://github.com/adobe/aem-core-wcm-components/files/3505632/dontlinkimage.zip)

**Closed by msagolj** 2019-08-15 13:25 UTC
