### ISSUE TITLE
[Container] components are added to multiple containers at once

### ISSUE THREAD

**Issue by EssersB** [adobe/aem-core-wcm-components#2422] opened 2023-01-10 08:47 UTC
## Bug Report

**Current Behavior**
When you have multiple containers on a page and want to add a component to one of them, sometimes the component is added to more than one container. 

Steps to reproduce:
1. Create a page with multiple containers on it.
2. Click on the `+` sign of one of the containers to open the dialog where you can select a component to insert. **Don't select a component yet!**
3. Close the dialog.
4. _Optionally: repeat step 2 and 3 with other containers_
5. Click on the `+` sign of another container than the container in step 2 so that you can insert a component.
6. Select a component to insert.

Result: the component selected in step 6 is added to all containers whose dialog has been opened.

**Expected behavior/code**
The component selected in step 6 is only added to the container in step 5.

**Environment**
- aem sdk api version 2022.9.8722.20220912T101352Z-220800
- Core Components version 2.19.2

**Possible Solution**
I believe it's a problem in the javascript of the container component since the request to add a component is sent multiple times and there are also the same amount of nodes created in the JCR.

**Comment by bpauli** [comment] 2023-01-11 13:22
Closing, as this is a duplicate of #2282

**Closed by bpauli** 2023-01-11 13:22 UTC
