### ISSUE TITLE
Carousel Component dialog broken when invoked under SPA Editor

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-core-wcm-components#421] opened 2019-01-09 21:54 UTC
## Bug Report

**Current Behavior**

When the carousel component is used in the AEM SPA editor, upon opening the dialog, the "Add Carouse Slide component" button doesn't (it does nothing, no JS error, etc.)

This results in the carousel component being uneditable.

**Expected behavior/code**

The carousel (and sub-slide components) to be normally authorable.

**Environment**
- AEM version and patch level: 6.4.2
- Core Components version: 2.2.0
- JRE version: Java 8

**Additional context / Screenshots**

![image](https://user-images.githubusercontent.com/1451868/50930894-28adad80-142f-11e9-8646-cd2f26b5df95.png)

**Comment by andreeadracea** [comment] 2019-01-10 12:39
@davidjgonzalez, unfortunately I was not able to reproduce the problem. Could you please explain more in detail the steps you did? 
Also, could you please check if you have the property cq:isContainer set to true for the carousel component?

**Comment by davidjgonzalez** [comment] 2019-01-10 17:51
@andreeadracea this should be set on the Carousel overlay `cq:Component` resource?

**Comment by jckautzmann** [comment] 2019-01-10 17:53
@davidjgonzalez exactly.

**Comment by davidjgonzalez** [comment] 2019-01-10 18:08
Is there a sample project you provide that I can install and try? (including a SPA app that implements the carousel?)

**Comment by jckautzmann** [comment] 2019-01-11 08:37
There is a carousel proxy component in We.Retail: /apps/weretail/components/content/carousel.
I'm not aware of a SPA app with a carousel.

**Comment by davidjgonzalez** [comment] 2019-01-11 21:10
@andreeadracea do you have whatever you tested the Carousel component in the SPA Editor in a fork/branch somewhere i could quickly test out?

**Comment by andreeadracea** [comment] 2019-01-14 14:45
@davidjgonzalez, I've tested the carousel on a normal AEM editor and there it worked. 
In order to use a carousel component in SPA you have to create a frontend app either in angular or react for it.
You can find an example of SPA project here [0], but it doesn't have a carousel component example and we are not aware of any SPA app implementing the carousel. 
[0]: https://github.com/adobe/aem-sample-we-retail-journal

**Comment by davidjgonzalez** [comment] 2019-01-15 16:43
@andreeadracea I know the carousel works on the "normal" Page Editor :)  This issue is specifically about the carousel dialog working in the **SPA Editor**.

I take from this thread, you were unable to reproduce this [1] in SPA Editor because you haven't tried reproducing it in SPA Editor? 

[1] https://github.com/adobe/aem-core-wcm-components/issues/421#issuecomment-453082176

**Comment by msagolj** [comment] 2019-01-16 12:31
Hi @davidjgonzalez , @andreeadracea is not available next 2 days so I will answer for her as we had a look at it together. 

> I take from this thread, you were unable to reproduce this [1] in SPA Editor because you haven't tried 
> reproducing it in SPA Editor?

Correct. As this is a common mistake people make when using the Carousel (see e.g. #341) to forget the 2 steps mentioned in the [readme ](https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel#enabling-carousel-editing-functionality) of the carousel we assumed its same case here, that's why it was suggested that you check if you have cq:isContainer set and the event listeners defined in your proxy..

Is there any git repo/content package/example site of your current work so we can have a look at it ? For now it seems to me that its missing some clientlib settings.

**Comment by msagolj** [comment] 2019-01-17 16:13
Hi @davidjgonzalez , had a deeper look with @pfauchere from SPA. 

The problem is that the carousel dialog [expects ](https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/commons/editor/dialog/childreneditor/v1/childreneditor/clientlibs/js/childreneditor.js#L180) at least one sub item, in the case of a new empty carousel its the placeholder.

In the non-SPA use case the carousel component's HTL script will [add ](https://github.com/adobe/aem-core-wcm-components/blob/master/content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel/carousel.html#L62)this missing resource 'on-the-fly'. This is obivously not happening in the SPA case.

The solution is to add this resource directly as a subnode of your SPA proxy carousel component e.g:

![subnode](https://user-images.githubusercontent.com/37147400/51330710-4f479600-1a78-11e9-9c88-79c50f14cc32.png). 

Here is a the (very minimalistic and incomplete ) react component I used to test it in the we-retail-journal example:

```
import React from 'react';
import {MapTo,Container} from '@adobe/cq-react-editable-components';

require('./Carousel.css')

 class Carousel extends Container  {

    get containerProps() {
        let containerProps = super.containerProps;
        containerProps.className = (containerProps.className || '') + ' cmp-carousel';
        return containerProps;
    }

    render() {        
        return (
            <div {...this.containerProps}> 
                <div className="cmp-carousel__content">
                
                    { this.childComponents }               
                </div>                                   
                { this.placeholderComponent }
            </div>
        );
    }
}

MapTo('we-retail-journal/components/carousel')(Carousel);
```

Please not that it extends `Container` and that you have to make sure that the root div has  `cmp-carousel` class name set so that all the related functions of carousel work properly.

**Comment by msagolj** [comment] 2019-02-06 14:12
assuming fixed, closing

**Closed by msagolj** 2019-02-06 14:12 UTC

**Comment by stlabelle** [comment] 2019-04-29 14:05
Hi @msagolj,

I know this topic is closed but I'm trying to do the same thing with Tabs component but even if I add the new component I can add tabs in the modal. Do you have any idea?

AEM: 6.4 SP2

Tabs.js
`import React from 'react';
import {MapTo, Container} from '@adobe/cq-react-editable-components';
  
/**
* Tabs React Component
* 
*/
class Tabs extends Container {
    render() {
        return (
			<div className="cmp-tabs" data-cmp-is="tabs"> 
		        <ol role="tablist" class="cmp-tabs__tablist" aria-multiselectable="false"></ol>       
		        <div data-cmp-hook-tabs="tabpanel" role="tabpanel">
		        	{ this.childComponents }
		        </div>
	        </div>
        );
    }
}
 
MapTo('wknd-events/components/content/tabs')(Tabs);`

**Comment by richardhand** [comment] 2019-04-29 15:27
@stlabelle -

> ... with Tabs component but even if I add the new component I can add tabs in the modal

Could you please clarify what you mean here by "new component"? I also assume you mean "can't" add tabs in the modal as that was the subject of the original issue?

Regarding, your example code, did you see @msagolj's https://github.com/adobe/aem-core-wcm-components/issues/421#issuecomment-455230521? The render function includes a placeholder such that if no child items are defined, there is still a placeholder rendered - the fix of the original issue. I don't see the same in your code.

**Comment by stlabelle** [comment] 2019-04-29 15:39
@richardhand So I extend the component in my project
![image](https://user-images.githubusercontent.com/15020906/56907844-23727e00-6a73-11e9-9fab-af24141bbacf.png)

![image](https://user-images.githubusercontent.com/15020906/56907810-10f84480-6a73-11e9-8a85-17065ce12498.png)

And aded that JS into my react component

![image](https://user-images.githubusercontent.com/15020906/56907911-41d87980-6a73-11e9-80a2-eddbcab2288b.png)

Now I can add the component on the page but when I click to add a tab in the modal, nothing is happening.

**Comment by richardhand** [comment] 2019-04-29 15:44
@stlabelle - it's probably not the fix, but in your latest example, the wrapper class name should be `cmp-tabs` not `cmp-carousel`.

**Comment by stlabelle** [comment] 2019-04-29 15:48
@richardhand I changed the class name and still have the same issue

**Comment by alissonxavierosfglobal** [comment] 2019-06-25 20:14
Hi guys,

Do you have an example that with Angular?

**Comment by claudiab** [comment] 2020-02-21 03:10
@stlabelle Did you end up fixing issue?

**Comment by Rohan179758** [comment] 2022-08-05 11:43
> @stlabelle -
> 
> > ... with Tabs component but even if I add the new component I can add tabs in the modal
> 
> Could you please clarify what you mean here by "new component"? I also assume you mean "can't" add tabs in the modal as that was the subject of the original issue?
> 
> Regarding your example code, did you see @msagolj's [#421 (comment)](https://github.com/adobe/aem-core-wcm-components/issues/421#issuecomment-455230521)? The render function includes a placeholder such that if no child items are defined, there is still a placeholder rendered - the fix of the original issue. I don't see the same in your code, but perhaps I'm misunderstanding.

Can you give the code in typescript ?
