### ISSUE TITLE
[Image] Image is not rendered when extension is in uppercase

### ISSUE THREAD

**Issue by pcastelog** [adobe/aem-core-wcm-components#1465] opened 2021-03-25 17:55 UTC
## Bug Report

**Current Behavior**
When an image with uppercase extension (.JPG, .PNG) is added to the image v2 component is not displayed.

**Expected behavior/code**
The image is displayed with uppercase or lower case extension.

**Environment**
Environment 6.5.6
Core Components 2.15.0
Java 8

**Possible Solution**
This happens because the configuration "AdaptiveImageServletMappingConfigurationFactory" is taken as it is to register the selectors in "AdaptiveImageServletMappingConfigurationConsumer". It can be fixed modifying the configuration but I see a better approach to modify the description of the field to explicitly request lowercase extensions and after that in the java class create the map duplicating the values for uppercase.

**Comment by bpauli** [comment] 2021-04-12 18:39
Hi @pcastelog, I'm not able to reproduce the issue.

If you're using the image v2 component the image url gets generated from the metadata of the asset/ file reference and the extension is created from the jcr:mimeType. This mime type property is extracted from the asset and usually not case-sensitive. For a PNG image for example this mimeType is always image/png regardless of uppercase or lowercase extension. In a second step the image v2 component is then using the mime type Service of AEM to create the final extension. On my environment this would always be a lowercase extension.

Some more information would be helpful. For example the value of the jcr:mimeType of your image or maybe you can share the image so I can try to reproduce the issue. Thanks!

**Comment by gabrielwalt** [comment] 2021-05-19 08:25
Closing this for now as there has been no answer so far and we couldn't reproduce the issue.
Please create a new issue or reopen this issue if this is still happening and you have more information.

**Closed by gabrielwalt** 2021-05-19 08:25 UTC
Labels: to clarify
