### ISSUE TITLE
In latest AEM ACS SDK version, issue configuring accordion and carousel core components

### ISSUE THREAD

**Issue by sarekha91** [adobe/aem-core-wcm-components#2255] opened 2022-07-14 12:21 UTC
## Bug Report

**Current Behavior**
On adding items to any multifield component from dialog, the added field is reflected in the backend and parsys but not immediately shown in the dialog field as expected. The fields appears on closing and re-opening the dialog. Observed in accordion and carousel core components.  Verified on WKND site with the latest SDK version, So the same extended components are also facing the same issue.

https://user-images.githubusercontent.com/109205525/178979535-c8cd0554-436b-414a-98b8-e754c20dc0d6.mp4

**Expected behavior/code**
Whenever we add a field in the dialog the field must appear and enabled for authoring.

**Environment**
- AEM As cloud service SDK version aem-sdk-2022.5.7575.20220530T152407Z-220500 (e.g. AEM 6.3 SP1 CFP2)
- Core Components version 2.19.2
- JRE version 11.0.10
- 
**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ahmed-musallam** [comment] 2022-07-18 23:22
I can verify this issue exists on latest AEMaaCS version as described in the ticket.
It seems the issue isn't an authoring blocker, but it certainly is a frustrating  UI experience.

**Comment by bpauli** [comment] 2022-09-12 12:08
This issue got fixed in https://github.com/adobe/aem-core-wcm-components/issues/2198

**Closed by bpauli** 2022-09-12 12:08 UTC
