### ISSUE TITLE
Infinite loop using @ChildResource on a proxy extension model

### ISSUE THREAD

**Issue by HitmanInWis** [adobe/aem-core-wcm-components#466] opened 2019-02-18 19:54 UTC
## Bug Report

**Current Behavior**
If I have model class A that has a `@ChildResource` of model class B, where B is a proxy extension of a WCM Core model, the result is an infinite loop attempting to inject the child resource B into model A.

**Expected behavior/code**
`@ChildResource` should work as expected, successfully injecting the child resource into a sling model regardless of whether it is a proxy extension of a WCM Core model

**Environment**
- AEM version and patch level: AEM 6.3 SP3
- Core Components version: 2.1.0

**Possible Solution**
Export model implementation classes so that WCM Core models can be extended w/o using the proxy pattern, which requires arbitrary coding to implement all interface methods (those implementations would be able to be directly inherited) and causes infinite loops like this as well as #239.

**Additional context**
Here are my model classes to reproduce the error.

Model Class "B" - a proxy extension of the WCM Core v2 Image component
```
package com.hs2solutions.aem.base.core.models;

import aQute.bnd.annotation.ConsumerType;
import com.adobe.cq.wcm.core.components.models.Image;

/**
 * Defines the {@code HS2Image} Sling Model used for the {@code hs2-aem-base/components/content/image} component.
 */
@ConsumerType
public interface HS2Image extends Image {

}

...

package com.hs2solutions.aem.base.core.models.impl;

import com.adobe.cq.wcm.core.components.models.Image;
import com.adobe.cq.wcm.core.components.models.ImageArea;
import com.hs2solutions.aem.base.core.models.HS2Image;
import org.apache.sling.api.SlingHttpServletRequest;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.models.annotations.Model;
import org.apache.sling.models.annotations.Via;
import org.apache.sling.models.annotations.injectorspecific.Self;
import org.apache.sling.models.annotations.via.ForcedResourceType;

import java.util.List;

@Model(
        adaptables = {Resource.class, SlingHttpServletRequest.class},
        adapters = {Image.class, HS2Image.class},
        resourceType = "hs2-aem-base/components/content/image"
)
public class HS2ImageImpl extends BaseModel implements HS2Image {

    @Self
    @Via(type = ForcedResourceType.class, value = "core/wcm/components/image/v2/image")
    private Image superTypeImage;

    @Override
    public String getSrc() {
        return superTypeImage.getSrc();
    }

    @Override
    public String getAlt() {
        return superTypeImage.getAlt();
    }

    @Override
    public String getTitle() {
        return superTypeImage.getTitle();
    }

    @Override
    public String getLink() {
        return superTypeImage.getLink();
    }

    @Override
    public boolean displayPopupTitle() {
        return superTypeImage.displayPopupTitle();
    }

    @Override
    public String getFileReference() {
        return superTypeImage.getFileReference();
    }

    @Deprecated
    @Override
    public String getJson() {
        return superTypeImage.getJson();
    }

    @Override
    public int[] getWidths() {
        return superTypeImage.getWidths();
    }

    @Override
    public String getSrcUriTemplate() {
        return superTypeImage.getSrcUriTemplate();
    }

    @Override
    public boolean isLazyEnabled() {
        return superTypeImage.isLazyEnabled();
    }

    @Override
    public String getExportedType() {
        return superTypeImage.getExportedType();
    }

    @Override
    public List<ImageArea> getAreas() {
        return superTypeImage.getAreas();
    }
}
```

Model class "A" - contains a reference to model class "B"
```
package com.hs2solutions.aem.base.core.models;

import aQute.bnd.annotation.ConsumerType;

/**
 * Defines the {@code HeroBanner} Sling Model used for the {@code hs2-aem-base/components/content/hero-banner} component.
 */
@ConsumerType
public interface HeroBanner {

    String getBackgroundSrc();
}

...

package com.hs2solutions.aem.base.core.models.impl;

import com.hs2solutions.aem.base.core.models.HS2Image;
import com.hs2solutions.aem.base.core.models.HeroBanner;
import com.hs2solutions.aem.base.core.models.annotations.via.OverriddenRequestPath;
import org.apache.sling.api.SlingHttpServletRequest;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.models.annotations.Model;
import org.apache.sling.models.annotations.Via;
import org.apache.sling.models.annotations.injectorspecific.ChildResource;
import org.apache.sling.models.annotations.injectorspecific.Self;

import javax.annotation.PostConstruct;

@Model(
        adaptables = {Resource.class, SlingHttpServletRequest.class},
        adapters = HeroBanner.class,
        resourceType = "hs2-aem-base/components/content/hero-banner"
)
public class HeroBannerImpl extends BaseModel implements HeroBanner {
    @ChildResource
    private HS2Image image;

    @Override
    public String getBackgroundSrc() {
        return image != null ? image.getSrc() : null;
    }
}
```

Sample of the stack trace:
```
18.02.2019 13:37:48.001 *WARN* [0:0:0:0:0:0:0:1 [1550518666253] GET /content/brand-2/language-masters/en.html HTTP/1.1] org.apache.sling.models.impl.ModelAdapterFactory Could not adapt to model
org.apache.sling.models.factory.ModelClassException: Adapting JcrNodeResource, type=hs2-aem-base/components/content/image, superType=null, path=/content/brand-2/language-masters/en/jcr:content/root/main-par/hero_banner/image to interface com.adobe.cq.wcm.core.components.models.Image failed, too much recursive invocations (>=20).
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:335)
	at org.apache.sling.models.impl.ModelAdapterFactory.getAdapter(ModelAdapterFactory.java:249)
	at org.apache.sling.adapter.internal.AdapterManagerImpl.getAdapter(AdapterManagerImpl.java:147)
	at org.apache.sling.api.adapter.SlingAdaptable.adaptTo(SlingAdaptable.java:104)
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrNodeResource.adaptTo(JcrNodeResource.java:178)
	at org.apache.sling.api.resource.ResourceWrapper.adaptTo(ResourceWrapper.java:180)
	at org.apache.sling.models.impl.ModelAdapterFactory.adapt(ModelAdapterFactory.java:991)
	at org.apache.sling.models.impl.ModelAdapterFactory.adaptIfNecessary(ModelAdapterFactory.java:963)
	at org.apache.sling.models.impl.ModelAdapterFactory.setField(ModelAdapterFactory.java:906)
	at org.apache.sling.models.impl.ModelAdapterFactory.access$100(ModelAdapterFactory.java:130)
	at org.apache.sling.models.impl.ModelAdapterFactory$SetFieldCallback.inject(ModelAdapterFactory.java:446)
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:541)
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:682)
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:394)
	at org.apache.sling.models.impl.ModelAdapterFactory.getAdapter(ModelAdapterFactory.java:249)
	at org.apache.sling.adapter.internal.AdapterManagerImpl.getAdapter(AdapterManagerImpl.java:147)
	at org.apache.sling.api.adapter.SlingAdaptable.adaptTo(SlingAdaptable.java:104)
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrNodeResource.adaptTo(JcrNodeResource.java:178)
	at org.apache.sling.api.resource.ResourceWrapper.adaptTo(ResourceWrapper.java:180)
	at org.apache.sling.models.impl.ModelAdapterFactory.adapt(ModelAdapterFactory.java:991)
	at org.apache.sling.models.impl.ModelAdapterFactory.adaptIfNecessary(ModelAdapterFactory.java:963)
	at org.apache.sling.models.impl.ModelAdapterFactory.setField(ModelAdapterFactory.java:906)
	at org.apache.sling.models.impl.ModelAdapterFactory.access$100(ModelAdapterFactory.java:130)
	at org.apache.sling.models.impl.ModelAdapterFactory$SetFieldCallback.inject(ModelAdapterFactory.java:446)
	at org.apache.sling.models.impl.ModelAdapterFactory.injectElement(ModelAdapterFactory.java:541)
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:682)
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:394)
	at org.apache.sling.models.impl.ModelAdapterFactory.getAdapter(ModelAdapterFactory.java:249)
	at org.apache.sling.adapter.internal.AdapterManagerImpl.getAdapter(AdapterManagerImpl.java:147)
	at org.apache.sling.api.adapter.SlingAdaptable.adaptTo(SlingAdaptable.java:104)
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrNodeResource.adaptTo(JcrNodeResource.java:178)
... (and on and on)
```

**Comment by HitmanInWis** [comment] 2019-02-18 19:58
Given that WCM Core components are already being versioned for breaking changes (at least that's the idea) what are the strong motivators for keeping this round-about pattern of extending WCM Core components by using `@Self` + `@Via` to re-adapt the current model to the super class model?

Or is there a better way to do what I'm attempting above?  I've asked around and this `@Self` + `@Via` method of extending WCM Core model classes was the only way people suggested.

**Comment by jckautzmann** [comment] 2019-02-20 16:40
hi @HitmanInWis , please have a look at our recommendations regarding the delegation pattern:
https://github.com/adobe/aem-core-wcm-components/wiki/Delegation-Pattern-for-Sling-Models
They are the best practices that we recommend to follow.

Back to your code: The first attempt to use the delegation pattern with @via seems ok as Sling will try to adapt the Resource to the Image model:
```
    @Self
    @Via(type = ForcedResourceType.class, value = "core/wcm/components/image/v2/image")
    private Image superTypeImage;
```
The 2nd attempt seems wrong as according to the Sling docs, @ChildResource will inject a child resource by name, not a model:
```
    @ChildResource
    private HS2Image image;
```
I would suggest that you refactor your code by following our delegation pattern guidelines.

**Comment by jckautzmann** [comment] 2019-02-20 16:41
I'm closing this issue for now. Please reopen it if needed.

**Closed by jckautzmann** 2019-02-20 16:41 UTC

**Comment by HitmanInWis** [comment] 2019-02-21 17:54
@jckautzmann I updated the proxy pattern in `HS2Image` to match the docs exactly, using
```
    @Self
    @Via(type = ResourceSuperType.class)
    private Image superTypeImage;
```

However, this does not solve the infinite looping problem.  Unless Im misssing something, this is indeed a bug.  In my `HeroBannerImpl` I can successfully use `@ChildResource` for a sling model that is *NOT* a proxy model - e.g.
```
    @ChildResource(injectionStrategy = InjectionStrategy.OPTIONAL)
    private Link link;
```
The above works just fine, successfully injecting the model, and not resulting in an infinite loop.
However, the `@ChildResource` below...
```
    @ChildResource(injectionStrategy = InjectionStrategy.OPTIONAL)
    private HS2Image image;
```
This fails with the infinite loop reported.

I've tested this with a `List` proxy extension as well, so it's not limited to the `Image` model.

This definitely feels like a bug.  One theory is that the `@ChildResource` injection is not honoring the `@Via` annotation on the injected proxy model class.  However, this could all be avoided if we simply allowed the WCM Core model implementation classes to be extended.

Can this ticket please be reopened?

**Comment by HitmanInWis** [comment] 2019-02-21 18:00
Also, can someone point me to any discussions that have happened on the merits of requiring this delegation pattern in sling model extensions?  I personally really, really dislike it, but I'm happy to set aside personal preference if there is objective, "real" (not just academic) reasons why we are forcing this upon the development community.

Downsides of this pattern are...
- It's obscure
- It adds complexity
- It requires a bunch of plumbing code to delegate functions to the proxy object, resulting in busy work and obscuring meaningful code
- It results in infinite loop bugs like #466 and #239 

Upsides of this pattern are?

**Comment by kwin** [comment] 2019-02-21 18:03
Upside: Impl classes stay implementation detail, only API needs to be exported. Clearer/smaller API. If the whole impl models would be exported maintaining backwards compatibility would be much harder.

**Comment by jckautzmann** [comment] 2019-02-21 18:28
@HitmanInWis As stated above, the following is not supposed to work:
```
    @ChildResource(injectionStrategy = InjectionStrategy.OPTIONAL)
    private HS2Image image;
```
Instead can you please try as follows:
```
    @Inject @Via(value = “image", type = ChildResource.class)
    private HS2Image image;
```
As @kwin pointed out, we don't want to make the implementations classes part of the API because it would be almost impossible to stay backwards compatible. The delegation pattern offers a way to still access the logic of the base objects.

**Comment by HitmanInWis** [comment] 2019-02-21 18:34
Let's talk about that though.

1) Changing the signature of any public functions will also change the interface, so there's no big difference there.  And if the interface is updated with a new function, one could argue that allowing extension automatically inherits the new function rather than an interface function that defaults to unsupportedoperationexception.
2) The Impl classes can store variables as private, to prevent direct access from subclasses.
3) So ultimately, it feels this really then only affects `protected` functions, which can largely be avoided.
4) There's already a versioning mechanism in place to overcome backward compatibility problems.

I'm not trying to be devils advocate to be a pain...I'm trying to be pragmatic and make sure we're getting "real" benefits rather than things that are academic.

**Comment by HitmanInWis** [comment] 2019-02-21 18:36
Also, @jckautzmann can you please show me why `@ChildResource` is not supposed to work with a proxy model object?  It works just fine with a non-proxy model object, so can you help me understand the difference?

**Comment by jckautzmann** [comment] 2019-02-21 18:48
@HitmanInWis The Sling Model docs [0] does not mention that the way you are using `@ChildResource` is supported. I also asked a Sling expert who confirmed that this use is not supported. I'm not a Sling expert so you may want to ask the Sling community directly to get a detailed answer.

[0] https://sling.apache.org/documentation/bundles/models.html

**Comment by HitmanInWis** [comment] 2019-02-21 19:18
The documentation on the linked page states:
- @ChildResource 
- Injects a child resource by name. If via is not set, it will automatically take resource if the adaptable is the SlingHttpServletRequest. If name is not set the name is derived from the method/field name.

If the following is not supposed to work...
```
    @ChildResource
    private Link link;
```
then what am I misunderstanding from the documentation?

Also, the above *does* work, and we use this extensively in client work.  Other people have been using this pattern since 2016 (https://placebo448.wordpress.com/2016/12/01/sling-model-automatic-adapting/).  It only doesn't work for the WCM Core proxy extensions.

Also, I attempted the recommended annotations
```
    @Inject
    @Via(value="link", type = ChildResource.class)
    private Link link;
```
but this injection fails with a `null` injection value every time.
```
	Caused by: org.apache.sling.models.factory.ModelClassException: No injector returned a non-null value!
```

**Comment by HitmanInWis** [comment] 2019-02-21 20:25
Ok, so I played around with this a bit more.  I think this might come down to the fact that `@ChildResource` is injecting a `Resource` object, and though our `HS2ImageImpl` adapts from a `Resource` the WCM Core `ImageImpl` that we are proxying does not support adapting from a `Resource` but only a `SlingHttpServletRequest` - see #467.  Though this is resulting in a strange infinite loop exception, giving no indication of the reason for failure, ultimately it wouldn't be able to inject anyway due to #467.

**Comment by vladbailescu** [comment] 2019-02-22 07:20
@HitmanInWis perhaps the biggest advantage of hiding the implementation and exposing it only through the delegation pattern is that, in most cases, you will be able to upgrade the Core Components without needing to recompile your customisation classes. Our studies have indicated that customers are weary to upgrade if that means that they might have to recompile and redeploy their custom bundles. By reducing the API surface to just the interfaces and making sure that we are only adding new methods (with default UOE) we support this while also allowing ourselves the liberty to change the implementation (including public/protected methods) as we see fit/convenient.

Regarding #467, we would very much appreciate a contribution for allowing models to adapt from `Resource` as well, that would probably be the fastest way to get this into the Core Components in case you need it for your project.

**Comment by jckautzmann** [comment] 2019-02-22 09:17
@HitmanInWis From the error message I noticed that the superType is null: 
```
org.apache.sling.models.factory.ModelClassException: Adapting JcrNodeResource, type=hs2-aem-base/components/content/image, superType=null, path=/content/brand-2/language-masters/en/jcr:content/root/main-par/hero_banner/image to interface com.adobe.cq.wcm.core.components.models.Image failed, too much recursive invocations (>=20).
```
Did you set the super type of your proxy HS2 image component to `core/wcm/components/image/v2/image`?
In order to reproduce this issue we would need more details about the 2 proxy components (hero banner and image): super type, HTL, … And details about the content structure in which they are used.

**Comment by jckautzmann** [comment] 2019-02-22 09:27
@HitmanInWis As you noted from the Sling Model docs, `@ChildResource` injects a child resource by name. I understand that it injects an object of type `Resource`. I don't see in the docs that the type can be something else, like a model.
@justinedelson As a Sling Model expert, could you please shed some light on this? Maybe it is supported and the docs should be updated.

**Comment by raducotescu** [comment] 2019-02-22 10:12
@HitmanInWis, `@ChildResource`, like already mentioned and specified in the documentation, injects a `Resource` and not a model. I can't see anywhere in the code that a model would be returned, therefore I highly doubt that the code example from https://github.com/adobe/aem-core-wcm-components/issues/466#issuecomment-466130047 works correctly.

**Comment by HitmanInWis** [comment] 2019-02-22 12:54
@vladbailescu I'm doubtful that many clients will use WCM Core components without at least some level of coding (i.e. base level styling) so Im not sure how valid the argument of "the code will need to be recompiled after you upgrade WCM Core version" is.   Again, I understand the textbook reasons why WCM Core is doing it this way, I'm questioning whether it's practical.  However, it appears I am clearly in opposition to everyone else's opinion, so I'll stand down on my request to expose the Impls for extension.  Regarding #467, I think one of the big challenges on that one is https://issues.apache.org/jira/browse/SLING-8279.  If a Resource stored the context of the current request when applicable, our sling models could more easily depend primarily on `Resource` rather than requiring a `Request` to adapt.  Without SLING-8279, we could get the models to work in back end processes, but annotations like `@ChildResource` will still be insufficient b/c they do not pass the `request` which is often needed by models for full functionality.  That said, maybe we need a new `@ChildRequest` annotation :).

@jckautzmann Yes, the super type of HS2 Image is `core/wcm/components/image/v2/image`.  The model works perfectly well stand-alone, just not in the `@ChildResource` case.  However, as I mentioned in my latest comment above, Im starting to think this is more because the `@ChildResource` attempts to adapt a model from a `Resource` and thus when `HS2Image` is adapted from a `Resource` and then attempts to do `@Self` to create the proxy object it fails b/c WCM Core `Image` cannot adapt from a `Resource`

@raducotescu I recommend you attempt the code example before (effectively) calling me out as being untruthful.  The code example of injecting a sling model using `@ChildResource` works, and we've done this extensively to inject child models (and even `java.util.List` of child models) on client work.

**Comment by HitmanInWis** [comment] 2019-02-22 13:05
Also, until #467 is addressed (thank you Vlad for the recommendation to produce a PR) I think this issue (#466) can remain closed because this simply *cant* work until the WCM Core components support adapting from `Resource`.

**Comment by jckautzmann** [comment] 2019-02-22 14:51
I spent some more time investigating this issue:
- I created a setup with the code from the initial comment
- I created a  hs2herobanner proxy component, which has an HTL script as follows:
```
<div class="my-hero-banner"
     data-sly-use.banner="com.adobe.cq.wcm.core.components.models.HeroBanner"
     data-sly-use.template="core/wcm/components/commons/v1/templates.html">
    <img src="${banner.backgroundSrc}"/>
</div>
```
- I created a  hs2image proxy component, which has `core/wcm/components/image/v2/image` as super type
- I added the following 2 nodes to a page: `herobanner` (parent) and `image` (child):
```
"herobanner": {
    "jcr:primaryType": "nt:unstructured",
    "sling:resourceType": "core/wcm/components/hs2herobanner",
    "image": {
        "jcr:primaryType": "nt:unstructured",
        "fileReference": "/content/dam/we-retail/en/activities/biking/enduro-trail-jump.jpg",
        "sling:resourceType": "core/wcm/components/hs2image"
    }
}
```
I requested the page and got the following errors (snippets):
```
Caused by: org.apache.sling.models.factory.MissingElementsException: Could not inject all required fields into class com.adobe.cq.wcm.core.components.models.HS2ImageImpl
…
Could not inject private com.adobe.cq.wcm.core.components.models.Image com.adobe.cq.wcm.core.components.models.HS2ImageImpl.superTypeImage
…
Could not adapt from class org.apache.sling.models.impl.via.AbstractResourceTypeViaProvider$ResourceTypeForcingResourceWrapper to interface com.adobe.cq.wcm.core.components.models.Image
```

I then made ImageImpl (v1 and v2) adaptable from `Resource.class`: for the test sake, I removed all the logic from the 2 implementations so the methods only return strings.
I requested the page: the herobanner rendered as expected and there was no errors in the logs.

This confirms what @HitmanInWis  suspected: it fails because WCM Core Image cannot adapt from a Resource (#467).

**Comment by HitmanInWis** [comment] 2019-02-22 15:35
FWIW the current WCM Core development is already causing breaking changes even using the proxy pattern.

Just updated a codebase from 2.1.0 to 2.3.0 and there are new interface functions in both `Page` and `Image` that are littering the log file with `Caused by: java.lang.UnsupportedOperationException: null` due to new interface functions that are not yet implemented in my proxy extensions.  Of course the updates to my proxy extensions are simple enough to make, but I think we're fooling ourselves if we're saying the current mechanism of proxy extension is accomplishing backward compatibility.

**Comment by HitmanInWis** [comment] 2019-02-22 15:52
Hitting this with `Title` as well.  Very practical example that we probably should be digging into (perhaps in a separate thread) if we want to make WCM Core components truly backward compatible.

Use case:
- Starting with WCM Core 2.1.0
- `customtitle` component that extends `core/wcm/components/title/v2/title`
- No HTML or Dialog file in `customtitle`
- `CustomTitle` model that is a proxy extension of `Title` and always uppercases the title.
- Now upgrade to WCM Core 2.3.0
-- This adds a new "Link" field to the dialog, which is inherited by `customtitle`
-- This adds new link functionality to the `title.html` HTL, which is inherited by `customtitle`
-- This adds `default String getLinkURL() { throw new UnsupportedOperationException();  }` to the `Title` interface in WCM Core, which is inherited by `CustomTitle`
--- `CustomTitle` does *not* inherit the functionality of `getLinkURL()` due to the proxy extension pattern
- Deploy to AEM without any code changes

The results of this use case are:
- All existing `customtitle` components litter the logs with `java.lang.reflect.InvocationTargetException: null` caused by `java.lang.UnsupportedOperationException: null at com.adobe.cq.wcm.core.components.models.Title.getLinkURL(Title.java:75)`
- Perhaps more importantly, authors have a new `Link` field on the `customtitle` dialog *that does nothing* meaning we've introduced a bug.

I would argue that allowing direct extension of the WCM Core `TitleImpl` model at least solves this with a simple build (but yes, the build is indeed required).  If we assume the proxy pattern, though, to avoid the required build, then we also need to prevent bugs like this by being much more diligent in our versioning process for these components.

**Comment by jckautzmann** [comment] 2019-02-22 16:04
@HitmanInWis Could you please create a new issue to discuss this? Mixing different topics (even related) in the same issue is confusing.

**Comment by HitmanInWis** [comment] 2019-02-25 19:02
Sure @jckautzmann - opened new issue #480 for this discussion.
