### ISSUE TITLE
Issue in OOTB breadcrumb component

### ISSUE THREAD

**Issue by Lovepreet1994** [adobe/aem-core-wcm-components#1210] opened 2020-10-13 05:13 UTC
Hi Everyone,

Greetings!!
We are facing issue with OOTB breadcrumb component. We have a requirement where we need to include breadcrumb component in initial layout of template where we can set “Navigation start level” for pages. But when we try to set navigation below 5 then we are getting exception on template (Although functionality is working fine on page level when we set any navigation level).
Getting below exception while setting level below 5:-

Error Message:
org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: Operands are not of the same type: comparison is supported for Number types only.

I have tried on we-retail template and there also getting same exception.
Does anyone face same kind of issue. Any pointers would be helpful.
[](url)

**Comment by ky940819** [comment] 2020-10-15 01:45
I think this is a duplicate of #1146 
I can confirm the same result that you experience with 2.11.0, but not in current development.

**Comment by bpauli** [comment] 2020-10-15 13:24
@Lovepreet1994, I was not able to reproduce the exception on my environment. Can you please share some more details (core component version, aem version etc.)? It would be also very helpful if you can provide a content package where we can reproduce the issue or detailed step by step guide. Thanks!

**Comment by Lovepreet1994** [comment] 2020-10-16 14:04
Hi,

I am using AEM 6.5.5 and core components version is 2.8.0. PFA content package for template.

Regards,
Lovepreet

**Comment by Lovepreet1994** [comment] 2020-10-16 14:05
@bpauli  I am not able to attach content package.

**Comment by ky940819** [comment] 2020-10-16 15:17
Here is a video of how to reproduce the result.
This uses AEM 6.5.6.0 + CC 2.11.1
https://streamable.com/c8k8kj

Again, this issue does not occur in current dev branch.

**Comment by msagolj** [comment] 2020-10-22 15:41
@ky940819 thx, for verifying. Closing the issues since its already fixed in dev branch and will be part of next release (presumably 2.12.0 )

**Closed by msagolj** 2020-10-22 15:41 UTC
Labels: to clarify
