### ISSUE TITLE
Cannot edit components in nested Accordion

### ISSUE THREAD

**Issue by tavleensingh4** [adobe/aem-core-wcm-components#2285] opened 2022-08-29 01:58 UTC
## Bug Report

**Current Behavior**
- Drop an accordion component on a page
- Add a few components in the accordion. Add another accordion inside the first accordion
- Re-arrange the items inside the inner accordion from the panel control
- The items inside the inner accordion are not editable except the first one

If an accordion component has another accordion inside it, then the items of the inner accordion are not editable after re-arranging them from the panel control

**Expected behavior/code**
User should be able to select/edit the items inside the inner accordion.

**Environment**
- AEM version 6.5 SP 6.5.13
- Core Components version 2.20.8
- JRE version 11

![accordion](https://user-images.githubusercontent.com/6603115/187108594-9f53b001-2ff5-4cb8-b1fe-538b616212c7.png)

**Comment by bpauli** [comment] 2022-09-01 20:16
Hi @tavleensingh4, can you please provide a screen recording of this issue as I was not able to reproduce it? Thanks!

**Comment by bpauli** [comment] 2022-09-12 05:45
@tavleensingh4 Can you please provide an update or can I close this issue? Thanks!

**Comment by tavleensingh4** [comment] 2022-09-12 09:21
@bpauli Please refer the attached screen recording
[screen-capture.zip](https://github.com/adobe/aem-core-wcm-components/files/9546627/screen-capture.zip)
Thanks.

**Comment by bpauli** [comment] 2022-09-15 09:22
@tavleensingh4 Thank you for the recording. I was now also able to reproduce the issue. It's a bug in the editor we need to tackle.

**Comment by bpauli** [comment] 2022-09-15 09:24
@adobe export issue to Jira project SITES as Bug

**Comment by vladbailescu** [comment] 2022-12-19 12:58
To work around this bug one can (temporarily) make all the child/inner accordion tabs/panels exapanded:
![image](https://user-images.githubusercontent.com/3670963/208431383-2a6820cd-fc27-44b2-a236-80c531982a0a.png)
this will allow editing of all child items:
![image](https://user-images.githubusercontent.com/3670963/208431479-a26a8eee-66f3-44e5-a834-09e5d19a77cb.png)

**Closed** 2022-12-20 17:09 UTC
Labels: bug, in review
