### ISSUE TITLE
Embeddable component - Design dialog not coming

### ISSUE THREAD

**Issue by nishneo** [adobe/aem-core-wcm-components#1633] opened 2021-06-16 07:58 UTC
## Bug Report

**Current Behavior**
Trying to extend the Embed component by adding newly embeddable. When creating new embeddable design dialogs, tabs for new embeddable are not coming up when selecting them in the dropdown

**Expected behavior/code**
The expectation was design dialogs should work as it works for Video embeddable

**Environment**
 - AEM Cloud
 - Core Components version - 2.16.4
 - JRE version (e.g. Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS))

**Additional context / Screenshots**
![image](https://user-images.githubusercontent.com/3760388/122180991-8ec37800-cea6-11eb-96a6-d6f3f48ce0a7.png)

**Comment by bartoszglow** [comment] 2021-06-16 08:00
@adobe export issue to Jira project SITES as Story

**Comment by bpauli** [comment] 2021-06-16 08:57
@nishneo There was an issue which got fixed in 2.16.0. (see https://github.com/adobe/aem-core-wcm-components/pull/1524) Can you please provide a content package with your custom embeddable which is not displayed in the dialog? Thanks!

**Comment by glasert** [comment] 2021-06-16 09:32
@adobe export issue to Jira project SITES

**Comment by slavvka** [comment] 2021-06-16 16:15
@adobe export issue to Jira project SITES

**Comment by nishneo** [comment] 2021-06-16 16:31
[embedRT_pkg (1).zip](https://github.com/adobe/aem-core-wcm-components/files/6664464/embedRT_pkg.1.zip)

@bpauli Attaching reference package

**Comment by bpauli** [comment] 2021-06-17 11:34
@nishneo The attached package contains only the vide embeddable. My understanding based on your screenshot you hat problems with the Form Widget embeddable, right?
However there was also one property missing in video embeddable so the design dialog always showed the video tab regardless which embeddable was enabled by the policy configuration. 
![image](https://user-images.githubusercontent.com/689884/122388927-a5ce9c80-cf70-11eb-82ff-de3ca704bd88.png)

**Closed** 2021-06-17 12:10 UTC
Labels: needs-clarification

**Comment by hcl63755** [comment] 2021-06-17 14:56
Hi @bpauli 
The issue is when embed component is extended by creating a new embeddable, it is breaking in design dialog as the new embeddable tab(in this case : video) is not getting show/hide on the selection of 'Video' option from 'Allowed Embeddables' dropdown.
Expected behavior/code
The expectation was design dialogs should work as it works for Youtube(OOTB) embeddable

Below is the screenshot for your reference. Even if the 'Video' option is not selected, 'Video' tab is showing.
![image](https://user-images.githubusercontent.com/85663482/122419711-bef33f80-cfa8-11eb-96d8-b8e26a1c9542.png)

Added the same property as mentioned in the previous comment. But still the behavior is same.
![image](https://user-images.githubusercontent.com/85663482/122420907-a2a3d280-cfa9-11eb-8e81-c1babdbeb505.png)

**Comment by hcl63755** [comment] 2021-06-21 07:37
Hi @bpauli,

The issue is now fixed after uploading the latest update on the core components. 
Thank you!!
