### ISSUE TITLE
[Tabs] After adding a Tabs component, only the first component on page can be authored

### ISSUE THREAD

**Issue by ArtixZ** [adobe/aem-core-wcm-components#779] opened 2019-10-01 18:52 UTC
## Bug Report

**Current Behavior**
After adding a Tabs component(which has editor-hook), only the first component on page(a big page parsys) can be authored. Others are marked as `is-disabled`.

It's because `getPanelContainerType`(attached link next) will try to iterate in its children to find out if there is a match. It means not only the Tabs component itself, but the page(the big page parsys) will be marked as a panel container as well, and only enable the first(based on activeIndex) component.

https://github.com/adobe/aem-core-wcm-components/blob/798d3947af9a83b53ce60fe7dd04908c8a4a4ec2/content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelcontainer/v1/js/panelContainerUtils.js#L113

**Expected behavior/code**
All the components in the page should be author-able.

**Environment**
- AEM version and patch level (e.g. AEM 6.4.3)
- Core Components version (e.g. 2.4.0. it's in master branch as well)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Possible Solution**
Check if the container is registered in editor-hook. If it is, run `updatePanelContainerOverlayState`. Otherwise, don't.

The `name` in panelcontainer.js at editorhook folder should be the same as name of the editor(component).

```javascript
        var panelContainerTypes = CQ.CoreComponents.panelcontainer.v1.registry.getAll();
        
        for (var i = 0; i < editables.length; i++) {
            var editable = editables[i];

            if (CQ.CoreComponents.panelcontainer.v1.utils.isPanelContainer(editable) && panelContainerTypes.findIndex(function(item){ return item.name === editable.name })>-1) {
                updatePanelContainerOverlayState(editable);
            }
        }
```

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

<img width="1564" alt="Screen Shot 2019-10-01 at 5 05 00 PM" src="https://user-images.githubusercontent.com/11360096/66000675-f2590800-e46d-11e9-80d8-198805b7f4c4.png">

Only Image component can be activated for editing. Clicking on Tabs or Video component won't do anything.

**Comment by ArtixZ** [comment] 2019-10-01 18:53
https://github.com/adobe/aem-core-wcm-components/blob/798d3947af9a83b53ce60fe7dd04908c8a4a4ec2/content/src/content/jcr_root/apps/core/wcm/components/commons/editor/clientlibs/panelcontainer/v1/js/contentTree.js#L56

**Comment by andreeadracea** [comment] 2019-10-15 12:12
@ArtixZ, unfortunately I was not able to reproduce your issue. I attached a video with the steps I did in order to reproduce it.
Please let me know if the steps you did in order to face this issue are different that what I did.

[Tabs.mov.zip](https://github.com/adobe/aem-core-wcm-components/files/3729124/Tabs.mov.zip)

**Comment by ArtixZ** [comment] 2019-10-23 16:35
@andreeadracea Thanks for getting back!

It works just because you happen to have a different DOM structure:
<img width="490" alt="Screen Shot 2019-10-23 at 12 16 32 PM" src="https://user-images.githubusercontent.com/11360096/67414107-6af44580-f590-11e9-87bf-dffd5a942398.png">

You will reproduce the issue if you delete ```<div class="aem-Grid aem-Grid--12 aem-Grid--default--12">``` in your page.


And this is the structure for us:
<img width="492" alt="Screen Shot 2019-10-23 at 12 21 04 PM" src="https://user-images.githubusercontent.com/11360096/67414142-7e9fac00-f590-11e9-9998-35fd33bf802f.png">

You can see, Tab component will be a children of an editable when execute this code: ```var children = editable.dom[0].children;```

It means the layout container itself is marked as panelContainer, because there is a Tab component being a direct children.

**Comment by ArtixZ** [comment] 2019-10-24 14:02
Does it have to be in an editable template?

**Comment by ArtixZ** [comment] 2019-10-24 14:07
Sorry this is the correct screenshot for us:
<img width="503" alt="Screen Shot 2019-10-24 at 9 57 00 AM" src="https://user-images.githubusercontent.com/11360096/67493534-ff6caf80-f645-11e9-8350-137a02fb6134.png">

**Comment by ArtixZ** [comment] 2019-10-24 14:15
@andreeadracea Thanks for getting back!

It works just because you happen to have a different DOM structure, where Tab component is not a direct children:
<img width="490" alt="Screen Shot 2019-10-23 at 12 16 32 PM" src="https://user-images.githubusercontent.com/11360096/67414107-6af44580-f590-11e9-87bf-dffd5a942398.png">

You will reproduce the issue if you delete ```<div class="aem-Grid aem-Grid--12 aem-Grid--default--12">``` in your page.


And this is the structure for us:
<img width="503" alt="Screen Shot 2019-10-24 at 9 57 00 AM" src="https://user-images.githubusercontent.com/11360096/67493534-ff6caf80-f645-11e9-8350-137a02fb6134.png">

You can see, Tab component will be a children of an editable when execute this code: ```var children = editable.dom[0].children;```

It means the layout container itself is marked as panelContainer, because there is a Tab component being a direct children.

**Comment by ArtixZ** [comment] 2019-10-24 14:15
Does it have to be in an editable template?

**Comment by andreeadracea** [comment] 2019-11-01 14:54
Hi @ArtixZ,

I tried to reproduce your issue doing what you suggested, but unfortunately I was not able. 
I've created a page which looks like this and I'm able to edit the tab component
![Screenshot 2019-11-01 at 16 50 55](https://user-images.githubusercontent.com/20905167/68033359-3424da80-fcc8-11e9-95ba-45e115df3403.png)

**Comment by vladbailescu** [comment] 2019-11-06 17:08
I was unable to reproduce this either. I tried a simple page with a parsys and two components beneath it:

![image](https://user-images.githubusercontent.com/3670963/68320442-4041db00-00c0-11ea-815f-8c3c94cc002e.png)

I'm closing this issue for now, I'd be happy to reopen it should you provide a small content package that allows us to reproduce it.

**Closed by vladbailescu** 2019-11-06 17:08 UTC
Labels: bug, to clarify

**Comment by powsurfer70** [comment] 2023-03-28 16:03
For us, the solution was as simple as adding the core clientlib embed to our proxied component as the README says. 

```
<sly data-sly-use.clientlibs="${'com.adobe.cq.wcm.core.components.models.ClientLibraries' @ categories='core.wcm.components.tabs.v1'}">
  ${clientlibs.jsAndCssIncludes @ context="unsafe"}
</sly>
```

**Comment by spoint-twilio** [comment] 2025-03-28 20:58
Hey team ! 
I am encountering the same issue
@ArtixZ @powsurfer70 How did you fix it ?

Thanks y'all !
