### ISSUE TITLE
Resources Clientlib for Favicon resolves to an unexpected path when Clientlib has dependencies

### ISSUE THREAD

**Issue by pmichelotti** [adobe/aem-core-wcm-components#1183] opened 2020-09-23 17:07 UTC
## Bug Report

**Current Behavior**
Given the following:

* Two clientlibraries a.site and a.dependencies where the path to each is /apps/client/clientlibs/site and /apps/client/clientlibs/dependencies respectively 
* That a.site is dependent on a.dependencies
* A template whose web resources client library is set to a.site

When resolving the path to the web resources directory the path resolves to the path of a.dependencies and not a.site.

**Expected behavior/code**
That the path should resolve to that of a.site

**Environment**
- AEM version and patch level AEM 6.5.5
- Core Components version 2.11.0
- JRE version 1.8

**Possible Solution**
This is being caused by the transitive resolution of the HTML Library occurring on line 144 of https://github.com/adobe/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v2/PageImpl.java

Either the resolution should not be transitive or the implementation should be taking the last result and not the first result.

**Comment by kwin** [comment] 2020-09-24 05:31
I think this is a duplicate of #1172.

**Comment by msagolj** [comment] 2020-09-24 08:01
Closing since its a duplicate of #1172 as mentioned by @kwin.

**Closed by msagolj** 2020-09-24 08:01 UTC
