### ISSUE TITLE
[Button] [Accessibility] Accessibility tab has issue with the help text

### ISSUE THREAD

**Issue by abhishekagg19** [adobe/aem-core-wcm-components#1472] opened 2021-03-29 05:15 UTC
### Expected Behaviour
Help text in accessibility tab should not keep resizing on hover in the UI dialog.

### Actual Behaviour
In the Button component dialog Accessibility tab when users hovers on the help text dialog keep on resizing until users removes the cursor from the help text

#### Steps to Reproduce
1. Open Button component dialog
2. Navigate to Accessibility text
3. Hover over the help text of the Label field and observe that dialog size keeps on resizing

#### Platform and Version
Latest version of 2.15.2
Windows
Chrome Latest version

**Comment by msagolj** [comment] 2021-04-01 14:24
Tried with latest SDK quickstart and 6.5.7, not reproducible for me. what AEM version did you use ?

**Comment by gabrielwalt** [comment] 2021-04-07 10:32
This issue seems to be fixed in the latest version. But even if it wouldn't, the issue likely isn't the Core Component, but rather the AEM UI framework used by the Core Components.

**Closed by gabrielwalt** 2021-04-07 10:32 UTC
Labels: to clarify
