### ISSUE TITLE
Sling cannot find existing resourceType to render a core component example page

### ISSUE THREAD

**Issue by zajcu** [adobe/aem-core-wcm-components#817] opened 2019-10-28 10:36 UTC
## Bug Report

**Current Behavior**
After several deployment to AEM instance, Sling has an issue to render any component.

**Expected behavior/code**
Stable AEM instance after every deployment.

**Environment**
- AEM 6.5 with Service Pack 2
- Core Components version 2.6.0 and 2.7.0
- Java 11 Oracle
- no custom code

**Additional context / Screenshots**
- Restart instance could help, but this is not an option on production.
- Resource types exists in JCR (can be found by manual query)
- Reindex all possible OOTB index doesn't help

Example logs in error.log

```
28.10.2019 09:39:24.857 *ERROR* [XXX [1572255564853] GET /content/core-components-examples/library/accordion.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource JcrNodeResource, type=core-components-examples/components/page, superType=null, path=/content/core-components-examples/library/accordion/jcr:content
28.10.2019 09:40:28.433 *ERROR* [XXX [1572255628313] GET /editor.html/content/core-components-examples/library/text.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource ValueMapResource, type=cq/gui/components/coral/common/form/templatefield, path=/libs/settings/cq/search/facets/pages/jcr:content/items/template
28.10.2019 09:40:28.489 *ERROR* [XXX [1572255628313] GET /editor.html/content/core-components-examples/library/text.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource MergedResource [path=/mnt/overlay/wcm/core/content/editor/jcr:content/sidepanels/edit/items/tabs/items/componentsTab/items/componenttemplate, resources=[/libs/wcm/core/content/editor/jcr:content/sidepanels/edit/items/tabs/items/componentsTab/items/componenttemplate]]
28.10.2019 09:40:28.568 *ERROR* [XXX [1572255628313] GET /editor.html/content/core-components-examples/library/text.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource MergedResource [path=/mnt/overlay/wcm/core/content/editor/jcr:content/content/items/content/header/items/headerbar/items/styleselectorpopover, resources=[/libs/wcm/core/content/editor/jcr:content/content/items/content/header/items/headerbar/items/styleselectorpopover]]
28.10.2019 09:40:28.575 *ERROR* [XXX [1572255628313] GET /editor.html/content/core-components-examples/library/text.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource MergedResource [path=/mnt/overlay/wcm/core/content/editor/jcr:content/content/items/content/header/items/statusbar, resources=[/libs/wcm/core/content/editor/jcr:content/content/items/content/header/items/statusbar]]
28.10.2019 09:40:28.647 *ERROR* [XXX [1572255628313] GET /editor.html/content/core-components-examples/library/text.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource MergedResource [path=/mnt/overlay/wcm/core/content/editor/jcr:content/content/items/content/content/items/styleselector, resources=[/libs/wcm/core/content/editor/jcr:content/content/items/content/content/items/styleselector]]
```

**Comment by msagolj** [comment] 2019-10-28 13:34
@zajcu Unfortunately the issue description is to vague to act upon. What do you mean by 'several deployment' ? how many ? what did you deploy, the 'all' package, single packages, project archetype ? deployed manually or via maven ? you list 2.6 and 2.7 so was there an upgrade involved ?

Please provide reproducible steps.

**Comment by zajcu** [comment] 2019-10-29 06:12
Hi @msagolj thank you for response,
- Several I mean sometimes is after 4th deploy sometimes after 3rd.
- Deployed is core component the 'all' package or custom builded package from CC repository.
- Issue occurs on every environment, local on Windows and remote on Centos.
- Core component is in version 2.6 or 2.7, issue occurs in both.

I think there is some crash between SP2 + Java11 + Sling + Core Components, maybe someone on your side had this issue?

**Comment by msagolj** [comment] 2019-10-30 16:27
@zajcu sofar nobody reported similar issues and our setup for running integration tests on 6.5 does a teardown/reinstall of AEM for each run so no help from there either :)

I've been unable to replicate this on my local machine (Windows,  6.5.2 author/nosamplecontent, CC 2.7.0, JDK 11.05, series of installs of 'all' package using package manager, verified via component library pages).

This doesn't mean that your issue is invalid but for now it seems that core components are not the root cause.  If the problem persists for you I would suggest to report this issue via  [Adobe Enterprise Support](https://helpx.adobe.com/contact/enterprise-support.ec.html) as it might indeed be an issue with SP2  as you suggested.

**Comment by gabrielwalt** [comment] 2019-11-04 17:29
Closing this for now.

**Closed by gabrielwalt** 2019-11-04 17:29 UTC
Labels: to clarify

**Comment by karoldrazek** [comment] 2019-12-17 14:39
The exact issue with nice workaround (approved by Adobe Enterprise Support) is described here:
https://issues.apache.org/jira/browse/FELIX-6184

**Comment by bipinbitla** [comment] 2020-04-04 06:33
Did anyone find the real fix on this other than the work around ? We are facing same exact issue in our CI server for AEM 6.5 SP4.

**Comment by jillmoto** [comment] 2020-04-29 20:46
we are also having the same issue.
It happens on replication only but it doesn't always happen after replication
Logs when this happens are
*ERROR* org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource JcrNodeResource

**Comment by mt33** [comment] 2020-07-13 23:52
Facing the same issue in 6.5.5. After a few deploys, getting those damn errors:

```
13.07.2020 19:48:53.866 *ERROR* [10.0.2.2 [1594684133603] GET /editor.html/content/my-page.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource MergedResource [path=/mnt/overlay/wcm/core/content/editor/jcr:content/content/items/content/header/items/headerbar/items/styleselectorpopover, resources=[/libs/wcm/core/content/editor/jcr:content/content/items/content/header/items/headerbar/items/styleselectorpopover]]
```
which are OOTB resource types. Cleared `fsclassloader`, cleared `scriptcache`, but only a full AEM restart fixes it. Very damning for local dev. How can I debug this further?

**Comment by sandroconte** [comment] 2020-09-01 16:36
What is the fix to this issue?

**Comment by jckautzmann** [comment] 2020-09-02 06:36
This is not an issue of the Core Components. Please contact the official Adobe support channels so you will be able to track its resolution:
https://helpx.adobe.com/contact/enterprise-support.ec.html
