### ISSUE TITLE
Download Button Component- Wrong download filename with no extension on AEMaaCS environments

### ISSUE THREAD

**Issue by niteshgupta92** [adobe/aem-core-wcm-components#2208] opened 2022-06-07 02:38 UTC
We were using Core component 2.19.0 version in our project and recently moved to 2.19.2, the download button component downloads the original rendition of the asset(pdf, jpeg etc) with no extension and the when configured as "Display Inline", it does the same downloads the file "original" with no extension. This behaviour is observed on the AEMaaCS environments while it works fine on AEM 6.5.12 setup.

Can we please take a look at it and suggest us a resolution for it?

**Comment by msagolj** [comment] 2022-06-07 08:35
Im not able to reproduce the issue with 2.19.2 on AEMaaCS. You can test it here:
https://www.aemcomponents.dev/content/core-components-examples/library/core-content/download.html

The issue you described is actually the one that was fixed with the 2.19.2 patch release (see Issue #2161, PR #2162 ), but i see you commented in that PR as well. 2.19.2 was added in AEMaaCS release 7493. Is your instance on a version >= than this ?

**Comment by bpauli** [comment] 2022-06-24 13:59
Closing as we didn't received any update

**Closed by bpauli** 2022-06-24 13:59 UTC
Labels: needs-clarification
