### ISSUE TITLE
Container component issue

### ISSUE THREAD

**Issue by NirmalKumar22** [adobe/aem-core-wcm-components#2282] opened 2022-08-25 08:02 UTC
**Current Behavior**
Steps to reproduce - 

Inside any container component, click on insert component, a dialog will open with an option to add the allowed components, close the pop-up without adding the component.

Now add any component outside the container component.

Observation - Two components gets added to the page (One inside the container component and one outside the container)

**Expected behavior/code**
When adding a component(ex: Image) outside the container component, the component(Image) should be added separately and it should not added to the container component.

**Environment**
- AEM v2022.8.8316.20220818T100409Z-220700
- Core Components version (e.g. 2.20.8)
- JRE version (e.g. `Java(TM) SE Runtime Environment (11.0.6)`)

**Additional context / Screenshots**
![](https://user-images.githubusercontent.com/112066794/186607624-4e125670-9c8c-46b1-836e-4a1d66ef1cbc.png)

In the above screenshot, the showcase collection is a container component. I have tried adding a component inside the showcase component and closed the pop-up without adding the component. Then added the audio player component outside the showcase collection . This action also results in adding a Audio player component inside the showcase collection as you can see in the screenshot. This is not the expected behavior I believe. 

This issue is not only within our project, it happens with core Aem components. So this issue is from Adobe. Could you guys please look into this?

<img width="928" alt="Screenshot 2022-08-25 163721" src="https://user-images.githubusercontent.com/112066794/186649410-ebe83b18-edb6-4035-a9a2-0efde6eae3e0.png">

**Comment by bpauli** [comment] 2022-09-02 07:32
@NirmalKumar22 Thank you for spotting this issue. I was able to reproduce it and will have closer look. Seems to be an issue with the new insert component dialog which is outside of the core component project. Will keep you updated.

**Comment by bpauli** [comment] 2022-09-02 12:47
The issue will be fixed with the next Cloud release. SITES-7105

**Closed by bpauli** 2022-09-02 12:47 UTC
Labels: bug, done

**Comment by mwahlmueller-avocodo** [comment] 2023-01-02 09:38
@bpauli can you maybe give insights on which cloud-SDK-version the issue will be resolved? I am still facing the issue with cloud SDK _2022.11.9850.20221116T162329Z_ version.

**Comment by bpauli** [comment] 2023-01-05 14:03
@mwahlmueller-avocodo, I just checked the internal reference. The fix is part of the cq-ui-wcm-editor-content package version >= 1.2.296. This issue wasn't marked as release blocker and there was not regular cloud release (only maintenance releases) since 2022/10. A new version should be part of the 2023/01 release. Sorry for the delay.
