### ISSUE TITLE
request to picker.html is throwing error for both 2.8.0 and 2.9.0 version

### ISSUE THREAD

**Issue by irenebijo** [adobe/aem-core-wcm-components#1052] opened 2020-06-11 01:21 UTC
http://localhost:4502/mnt/overlay/cq/gui/content/coral/common/form/pagefield/picker.html?root=%2fcontent&selectionCount=single&_=1591837034973

Link field in Title component of core-wcm  is throwing the below error.

![image](https://user-images.githubusercontent.com/6331167/84334216-7a43f580-ab57-11ea-8d32-a5f9d7034ccc.png)

----------------Error Log------------
10.06.2020 19:57:42.451 *WARN* [0:0:0:0:0:0:0:1 [1591837062427] GET /mnt/overlay/cq/gui/content/coral/common/form/pagefield/picker.html HTTP/1.1] libs.granite.ui.components.coral.foundation.columnview Failed to wrap datasource for lookahead
org.apache.sling.api.scripting.ScriptEvaluationException: 
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:416) [org.apache.sling.scripting.core:2.0.56]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:184) [org.apache.sling.scripting.core:2.0.56]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:491) [org.apache.sling.scripting.core:2.0.56]
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552) [org.apache.sling.engine:2.6.20]
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44) [org.apache.sling.engine:2.6.20]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:82) [org.apache.sling.engine:2.6.20]
	at com.day.cq.wcm.core.impl.WCMDeveloperModeFilter.doFilter(WCMDeveloperModeFilter.java:119) [com.day.cq.wcm.cq-wcm-core:5.12.106.NPR-31870-B0001]
	at org.apache
.
.
.
.

10.06.2020 19:57:42.459 *ERROR* [0:0:0:0:0:0:0:1 [1591837062427] GET /mnt/overlay/cq/gui/content/coral/common/form/pagefield/picker.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught SlingException
java.util.regex.PatternSyntaxException: Illegal repetition near index 0
${empty param.exclude ? "/content/(catalogs|dam|launches|mac|publications|usergenerated|experience-fragments|communities|community-components|community-templates|forms|projects|phonegap|mobileapps|screens/(svc|blueprints)|entities|versionhistory)(/.*)?" : param.exclude }
^
	at java.util.regex.Pattern.error(Unknown Source)
	at java.util.regex.Pattern.closure(Unknown Source)

## Bug Report

**Current Behavior**
A clear and concise description of the behavior, including steps that are repeatable, and your setup; if applicable, proxy component pattern and component version.

**Expected behavior/code**
link should open the content path field

**Environment**
- AEM version and patch level (e.g. AEM 6.3 SP1 CFP2)
- Core Components version (e.g. 2.8.0)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

**Possible Solution**

**Additional context / Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by rajeevyadav2** [comment] 2020-06-11 01:48
Is this issue on 6.3?

**Comment by msagolj** [comment] 2020-06-11 10:58
@irenebijo can you please provide more info (AEM Version, core component version, jre ), I can't reproduce the error.

**Comment by msagolj** [comment] 2020-06-15 14:04
@irenebijo closing for now as its not reproducible. Please reopen if you can still reproduce and add the requested infos (AEM version, core comp version, Java Version)

**Closed by msagolj** 2020-06-15 14:04 UTC
Labels: to clarify
