### ISSUE TITLE
[Accessibility] [Carousel] Linked images and linked titles have different accessible names but serve the same purpose/have the same functionality.

### ISSUE THREAD

**Issue by LevelAccessA11y** [adobe/aem-core-wcm-components#1787] opened 2021-08-27 00:21 UTC
**Steps to Reproduce**
1. Enable NVDA screen reader.
2. Open page in Google Chrome.
3. Use TAB or SHIFT + TAB to navigate to the linked images in the "Teaser Slides" carousel.
4. Use TAB or SHIFT + TAB to the associated title element for the image.

**Current Behavior**
The accessible names for the image and title links are different, but serve the same purpose. This can be cumbersome and confusing for keyboard-only users and/or screen reader users as they navigate through the page.

**Expected behavior/code**
As the image and title links serve the same purpose, it is best practice to remove the link from the image. If a click of the image should activate the link, use Javascript to capture clicks.

**Environment**
Chrome 92, Windows 10, NVDA 2020.4 
AEM Core Components v. 2.17  

**Affected Users**
Screen reader users, keyboard-only users

**WCAG SC**
2.4.4 Link Purpose (In Context)

**Comment by gabrielwalt** [comment] 2022-01-07 09:13
This is because the carousel items are constructed with teasers, so this bug is a duplicate of #1712.

**Closed by gabrielwalt** 2022-01-07 09:13 UTC
Labels: enhancement
